### ISSUE TITLE
Transplant PX4 to stm32f4discovery error

### ISSUE THREAD

**Issue by dongdongbh** [PX4/Firmware#3027] opened 2015-10-20 05:05 UTC
Following https://pixhawk.org/modules/stm32f4discovery to Transplant PX4 to stm32f4discovery on windows,when i type "make archives",it prompt "No rule to make 'archives'. stop.".   Is there some makefile missed? How should solve this issue?

**Comment by lchish** [comment] 2015-10-20 20:42
This is a duplicate of the bug I posted just before you #3026 you can work around this at the moment by checking out an older version of the git repository.

**Comment by LorenzMeier** [comment] 2015-10-21 15:56
Closing this in favour of #3026.

**Closed by LorenzMeier** 2015-10-21 15:56 UTC
