### ISSUE TITLE
Intel Aero not retaining parameters after reboot

### ISSUE THREAD

**Issue by santiago3dr** [PX4/Firmware#8585] opened 2018-01-04 21:03 UTC
When flashing master 430cdad calibrations on all sensors and radio are required (1).
Successfully ran Gyro calibration (2).
Once calibrating and rebooting, all calibration values are lost (3).
Reverting to yesterdays master 757d905 all calibration values are restored WITHOUT having to re-calibrate (4).
![1](https://user-images.githubusercontent.com/13203106/34584137-6aec47f0-f14f-11e7-98cd-58fb6a9839d6.JPG)
![2](https://user-images.githubusercontent.com/13203106/34584141-6f389c64-f14f-11e7-8caa-d6af56a1cafb.JPG)
![3](https://user-images.githubusercontent.com/13203106/34584144-722aa17e-f14f-11e7-9c38-f97dda4e2bcf.JPG)
![4](https://user-images.githubusercontent.com/13203106/34584147-7419364e-f14f-11e7-921a-80f17adbcb69.JPG)

**Comment by dagar** [comment] 2018-01-04 21:05
Could you go to the param tree and do a full refresh? Now try to change a random parameter and save. After a reboot is that parameter preserved?

**Comment by santiago3dr** [comment] 2018-01-04 21:15
Flashed 430cdad and went to parameter tree, hit refresh, changed NAV_MC_ALT_RAD from 0.8 to 1.1
Did a power cycle on the vehicle and parameter reverted to default 0.8

**Comment by dagar** [comment] 2018-01-04 21:18
Thanks Santiago. So it seems I broke flash based parameter writing (intel aero only I believe), but it's still able to read successfully. I suspect this hack is the culprit - https://github.com/PX4/Firmware/commit/430cdada602ee5037f7b8f5c43b615e181400351

**Comment by dagar** [comment] 2018-01-04 21:29
https://logs.px4.io/plot_app?log=5a8b3640-a795-4386-ae2f-ec5c43fa2264

![image](https://user-images.githubusercontent.com/84712/34585093-5ef139e8-f16c-11e7-839a-14082a8fe0e7.png)

**Comment by LorenzMeier** [comment] 2018-01-04 21:41
Looks like the wrong file descriptor since Intel Aero does not have an SD. Board detection issue?

**Comment by dagar** [comment] 2018-01-04 22:47
I think a lot of the error messages aren't quite right for the Aero. This should be fixed in https://github.com/PX4/Firmware/pull/8586

**Comment by dagar** [comment] 2018-01-05 21:44
Surprisingly this doesn't seem to be related to the tinybson change.

1. Test build 1 (commit right before the bson encoder buffer)
   - https://github.com/PX4/Firmware/commit/08443c0
   - https://github.com/PX4/Firmware/compare/08443c0...master
2. Test build 2 (commit right before all recent param changes)
   - https://github.com/PX4/Firmware/commit/c8590e0
   - https://github.com/PX4/Firmware/compare/c8590e0...master

Which means the problem is somewhere in here. https://github.com/PX4/Firmware/compare/c8590e0...08443c0

**Comment by dagar** [comment] 2018-01-05 22:39
The perf counters seem to be the problem on aero.

**Comment by dagar** [comment] 2018-01-12 18:48
The header ordering somehow broke params on the Aero.

**Closed** 2018-01-12 22:46 UTC
Labels: bug, intel aero
