### ISSUE TITLE
FW: Cannot takeoff in mission mode anymore

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#4850] opened 2016-06-20 08:15 UTC
In mission mode the prop should start spinning and rev up once takeoff is detected.
This did not work anymore with the last stable release of QGC on the tablet.

**Comment by dagar** [comment] 2016-06-20 14:09
Did you have a takeoff waypoint? Hand launch or runway?

**Comment by tumbili** [comment] 2016-06-21 07:35
@dagar It had a takeoff waypoint and the user tried hand launch.

**Comment by LorenzMeier** [comment] 2016-06-21 07:44
I can't reproduce this in SITL:

```make posix gazebo_plane```

<img width="1120" alt="screen shot 2016-06-21 at 09 42 19" src="https://cloud.githubusercontent.com/assets/1208119/16221731/a661ff76-3794-11e6-8157-d0fded08e2b3.png">
<img width="1392" alt="screen shot 2016-06-21 at 09 42 34" src="https://cloud.githubusercontent.com/assets/1208119/16221736/a9a17e28-3794-11e6-9c33-d4ee91b5092b.png">

**Comment by LorenzMeier** [comment] 2016-06-21 20:21
I'm closing this as I think its was something else - the user couldn't arm at all in any mode. Reopen if it persists.

**Closed by LorenzMeier** 2016-06-21 20:21 UTC
Labels: bug, fixedwing
