### ISSUE TITLE
Camera feedback

### ISSUE THREAD

**Issue by jcooper21** [PX4/Firmware#5166] opened 2016-07-29 19:45 UTC
@LorenzMeier Is there any chance in getting camera feedback added to the version 1.5 milestone.  This would be great to have as we help test development of QGC mapping functionality.

**Comment by LorenzMeier** [comment] 2016-07-30 08:32
Yes, let's do that.

**Comment by jcooper21** [comment] 2016-09-01 22:50
@LorenzMeier One thing I forgot to mention here is that the feedback system would ideally include shutter count to compare how many pictures were taken against how many QGC calculated we should have taken in real time.

**Comment by LorenzMeier** [comment] 2017-04-30 12:02
@DonLakeFlyer We're sending CAMERA_TRIGGER messages. Are you processing these?

**Comment by LorenzMeier** [comment] 2017-05-01 13:01
Duplicate of #7164 now.

**Closed by LorenzMeier** 2017-05-01 13:01 UTC
Labels: enhancement
