### ISSUE TITLE
setpoint_accel plugin in px4

### ISSUE THREAD

**Issue by tuofeichen** [PX4/Firmware#3743] opened 2016-02-12 21:10 UTC
Hey guys,
I was wondering if the setpoint_accel plugin is supported by px4 firmware now. I was a little confused because:
1. According to this https://github.com/mavlink/mavros/blob/master/test_mavros/README.md, 
2, I followed the exact same procedure for sending out setpoint_accel as setpoint_velocity, but the SITL and Pixhawk both didn't seem to respond to it. Whereas setpoint_velocity works perfectly fine for me.

Thank you!

Best Regards,
Francis

**Comment by julianoes** [comment] 2016-02-15 13:26
I would say that's a duplicate of #3452, closing.

**Closed by julianoes** 2016-02-15 13:26 UTC
