### ISSUE TITLE
no rc detected on pixhawk v4 pro, pixhawk 1 , pixhawk mini v3 and pixhawk 2

### ISSUE THREAD

**Issue by dannyfpv** [PX4/Firmware#10134] opened 2018-08-03 14:19 UTC
install the new master on the four flight controllers and fail, if use the ac8f4426 version work propely
**To Reproduce**
flash the new firmware and the flight mode go to manual mode.

Add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/31113129/43647458-89fb57b0-96ec-11e8-90d9-c36591eb9d96.png)

![image](https://user-images.githubusercontent.com/31113129/43647773-7dfde0f8-96ed-11e8-98c1-808bd0a17d9c.png)

one (please complete the following information):**
the four frames f450 - Photo of the IMU / autopilot setup if possible.

@Tony3dr

**Comment by dagar** [comment] 2018-08-03 14:26
Likely a duplicate of https://github.com/PX4/Firmware/issues/10131.
See https://github.com/PX4/Firmware/pull/10132

**Comment by dagar** [comment] 2018-08-03 14:47
Please try master as of https://github.com/PX4/Firmware/commit/a6f93c30d9151d0d913868e74e48979cd89197c8.

**Comment by dagar** [comment] 2018-08-07 15:11
Fixed in master.

**Closed by dagar** 2018-08-07 15:11 UTC
