### ISSUE TITLE
PX4/ecl v1.9.0 release blockers

### ISSUE THREAD

**Issue by dagar** [PX4/Firmware#11798] opened 2019-04-05 14:14 UTC
- [x] https://github.com/PX4/ecl/pull/578
 - [x] https://github.com/PX4/ecl/pull/593
 - [ ] ~~https://github.com/PX4/ecl/pull/505~~ UPDATE: pushed to post v1.9.0

**Comment by dagar** [comment] 2019-04-05 14:15
@priseborough @RomanBapst @mhkabir @CarlOlsson please update this issue with any outstanding PX4/ecl changes or issues needed before a v1.9.0 release.

**Comment by priseborough** [comment] 2019-04-07 21:39
https://github.com/PX4/ecl/pull/578 has been merged

https://github.com/PX4/ecl/pull/593 is awaiting test evidence from the author, but is otherwise a low risk change.

https://github.com/PX4/ecl/pull/505 is a more complex change and without proper testing including the revised logic for handling of optical flow timeouts could introduce bugs I am not comfortable with it being included in a stable release without significant testing.

**Comment by dagar** [comment] 2019-04-08 02:05
Thanks Paul.

@mhkabir @RomanBapst thoughts on testing https://github.com/PX4/ecl/pull/505 this week for release inclusion? Either way we should discuss an appropriate test plan.

**Comment by LorenzMeier** [comment] 2019-04-13 20:31
@RomanBapst Please help with testing where possible.

@dagar Any updates?

**Comment by mhkabir** [comment] 2019-04-13 20:38
Let's remove the optical flow PR from release. It will require more testing and work which I'm not able to contribute right now.

**Comment by dagar** [comment] 2019-04-13 20:40
We've arranged to get @PX4/testflights optical flow hardware (pmw3901), but I don't know the realistic time frame.

> Let's remove the optical flow PR from release. It will require more testing and work which I'm not able to contribute right now.

Sounds like we're bumping it for v1.9.0, but can we still try to get a test plan together for these items?

**Comment by LorenzMeier** [comment] 2019-04-13 20:41
@jkflying has done extensive testing of this - could you please pitch in here? We're flying this daily in Zurich.

**Comment by dagar** [comment] 2019-04-13 20:42
@mhkabir what about https://github.com/PX4/ecl/pull/593?

**Comment by dagar** [comment] 2019-04-13 21:34
> @jkflying has done extensive testing of this - could you please pitch in here? We're flying this daily in Zurich.

I've rebased https://github.com/PX4/ecl/pull/505 on current master. The branch ecl_PR-505 was created for testing PX4/Firmware side. https://github.com/PX4/Firmware/tree/ecl_PR-505

Binaries available here under artifacts. http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-compile/detail/ecl_PR-505/1/pipeline

**Comment by jkflying** [comment] 2019-04-14 07:01
I'll give this a flight tomorrow if the weather is ok, I don't forsee any issues caused by https://github.com/PX4/ecl/pull/505 though since the pmw3901 runs at ~40hz.

**Comment by jkflying** [comment] 2019-04-16 12:51
@dagar should I test the exact binaries? I usually increase tx/rx buffer sizes a bit because of our particular setup, but I can disable our log streaming, avoidance etc if it is important to use the exact binaries.

**Comment by dagar** [comment] 2019-04-16 13:29
@jkflying no, it's just for convenience.

**Comment by jkflying** [comment] 2019-04-16 14:21
Flight with PMW3901 was good. No weird twitches, seemed smooth, did multiple takeoffs with optical flow straight from the grass, did a mission with avoidance enabled. Everything seemed fine. Merging is OK from my side.

**Comment by mhkabir** [comment] 2019-04-16 14:26
@jkflying Can you post the logs on the ECL PR please?

**Closed** 2019-04-24 06:07 UTC
Labels: bug, ekf2, enhancement
