### ISSUE TITLE
px4flow testing, position control failed under I-NAV in v1.4.0 and above

### ISSUE THREAD

**Issue by dengzhijie** [PX4/Firmware#4962] opened 2016-07-02 10:08 UTC
Hello
I am testing px4flow (no GPS) on pixhawk which running I-NAV.It can be switched to posctl successfully(not ARMED).But after it was armed,when i changed to position control, the light turned to green and then to pink(purple?),and failed to hover.
Firmware version: v1.3.3, v1.4.0rc2,also tested in latest 1.4.0rc3, all failed.
 expecting for you help,thanks!

As a comparason, iNAV works without any problem using firmware v1.3.0/v1.3.1 or earlier. So anyting changed?
@iZhangHui @rolandash @eflyinghi @jgoppert

**Comment by dengzhijie** [comment] 2016-07-04 10:15
We tested v1.3.4 and v1.4.1 today,but the problem still remain.

**Comment by LorenzMeier** [comment] 2016-07-04 11:32
I quickly looked at the diff between 1.3.1 and 1.3.4 and can't really see anything substantial. Can you please re-test with 1.3.1 and make sure it still works?

**Comment by dengzhijie** [comment] 2016-07-05 10:16
@LorenzMeier I am sorry,we made a mistake.There are no problem of v1.3.1,v1.3.3 and v1.3.4.So the problem only exisits in v1.4.0 and the latest v1.4.1.

**Comment by dengzhijie** [comment] 2016-07-05 10:18
I changed the title just now to reflect the latest testing result.

**Comment by LorenzMeier** [comment] 2016-07-05 10:18
That makes a lot more sense. Can you try with the LPE estimator, because we will stop developing INAV soon?

**Comment by dengzhijie** [comment] 2016-07-05 11:25
@LorenzMeier We tested LPE under v1.4.0 and the latest v1.4.1,the same phenomenon to I-NAV

**Comment by LorenzMeier** [comment] 2016-07-05 11:26
Can you please read this page and check if you followed all recommendations?
http://dev.px4.io/flow_lidar_setup.html

**Comment by iZhangHui** [comment] 2016-07-06 09:11
@LorenzMeier This issue is caused by  [code here.](https://github.com/PX4/Firmware/blob/master/src/modules/commander/state_machine_helper.cpp#L674)
It only checks for gps_failure, so POSCTL flying with px4flow (no GPS) will always fall into fail-safe mode.

I'm able to fly when set parameter CBRK_GPSFAIL to 240024.

**Comment by LorenzMeier** [comment] 2016-07-06 09:19
@julianoes can you look into this?

**Comment by julianoes** [comment] 2016-07-06 09:32
Aha, I didn't think of this case. Is it correct that POSCTL should be allowed with a local position estimate whereas the auto modes should not be allowed without GPS?

**Comment by LorenzMeier** [comment] 2016-07-06 09:34
Yes, pretty much

**Comment by julianoes** [comment] 2016-07-13 18:35
@dengzhijie can you please #5058.

**Comment by dengzhijie** [comment] 2016-07-15 09:05
@julianoes We  tested LPE under the v1.4.1rc2 on pixhawk and MindPX  today,the problem was solved and it successed to POSCTL .
Really thank to your help!

**Comment by julianoes** [comment] 2016-07-15 13:22
@dengzhijie thanks for testing and reporting. I'll merge it then.

**Comment by julianoes** [comment] 2016-07-15 13:44
Resolved with https://github.com/PX4/Firmware/pull/5058.

**Closed by julianoes** 2016-07-15 13:44 UTC
Labels: bug
