### ISSUE TITLE
position mode through mocap

### ISSUE THREAD

**Issue by roseyangyu** [PX4/Firmware#12091] opened 2019-05-28 06:21 UTC
I use 1.8.2/1.9.0 firmware, v2 and v5 flight control. LPE is not used. I want to locate through MoCap. The accuracy of the mocap raw data is millimeter level. I sent the position to flight control via VISION_POSITION_ESTIMATE. Vehicle can enter position mode at rest, but when vehicle fly up, it can't hover accurately. I looked at Local_position's data with a QGC. The x,y axis occasionally mutates to more than 10 meters, with a greater change in height, generally changing at dozens of meters, and occasionally larger to more than 100 meters. How can I debug to make the plane hover steadily?

**Comment by julianoes** [comment] 2019-08-26 14:04
You need to add a logfile, otherwise it's hard to see what's going on.

**Comment by roseyangyu** [comment] 2019-08-27 09:27
There was no unlocking during testing because local_position displayed unreliable data.But I change mavlink_message.I send mocap rather than vision.Then I adjust mocap coordinate system to NED and turn PID.Vehicle can position well.

**Comment by julianoes** [comment] 2019-08-27 10:16
Ok thanks for the answer. Sounds like the issue is resolved and I can close it. Please re-open if the issue comes back.

**Closed by julianoes** 2019-08-27 10:16 UTC
Labels: more_info_needed, offboard, state estimation

**Comment by roseyangyu** [comment] 2019-08-28 01:05
OK,Thank you for your attention
