### ISSUE TITLE
Repeated RTL

### ISSUE THREAD

**Issue by ender-chen** [PX4/Firmware#4607] opened 2016-05-23 08:33 UTC
When Lost RC signal. It will go into RTL. But when it touched land, It will detect takeoff. and go into RTL again.

`bool set_nav_state(struct vehicle_status_s *status, const bool data_link_loss_enabled, const bool mission_finished,
		   const bool stay_in_failsafe)
{
	navigation_state_t nav_state_old = status->nav_state;

	bool armed = (status->arming_state == vehicle_status_s::ARMING_STATE_ARMED || status->arming_state == vehicle_status_s::ARMING_STATE_ARMED_ERROR);
	status->failsafe = false;

	/* evaluate main state to decide in normal (non-failsafe) mode */
	switch (status->main_state) {
	case vehicle_status_s::MAIN_STATE_ACRO:
		/* require RC for all manual modes */
		if ((status->rc_signal_lost || status->rc_signal_lost_cmd) && armed &&  !landed) {
			status->failsafe = true;

			if (status->condition_global_position_valid && status->condition_home_position_valid) {
				if (status->nav_state == vehicle_status_s::NAVIGATION_STATE_AUTO_RCRECOVER
						&& stay_in_failsafe) {
					status->rc_loss_finished = true;
				}
				if (!status->rc_loss_finished) {
					status->nav_state = vehicle_status_s::NAVIGATION_STATE_AUTO_RCRECOVER;
				} else {
					status->nav_state = vehicle_status_s::NAVIGATION_STATE_AUTO_RTL;
				}
			} else if (status->condition_local_position_valid) {
				status->nav_state = vehicle_status_s::NAVIGATION_STATE_LAND;
			} else if (status->condition_local_altitude_valid) {
				status->nav_state = vehicle_status_s::NAVIGATION_STATE_DESCEND;
			} else {
				status->nav_state = vehicle_status_s::NAVIGATION_STATE_TERMINATION;
			}

		} else {
			switch (status->main_state) {
			case vehicle_status_s::MAIN_STATE_ACRO:
				status->nav_state = vehicle_status_s::NAVIGATION_STATE_ACRO;
				break;

`

I think there is something wrong in lost signal condition "!landed". Because in RTL. When touched the land It is still uncompleted. But it will change to other navigator_mode. So I suggest Delete that condition.

**Comment by julianoes** [comment] 2016-05-26 19:03
Thanks for reporting. Is this easily reproducible in SITL or how did you find this?

**Comment by ender-chen** [comment] 2016-05-31 07:32
I test it with my plane. I just shutdown my rc controller, but it just repeated rtl. YES, I think you can reproducible in SITL.

**Comment by julianoes** [comment] 2016-05-31 07:36
@ender-chen: can you share logs please and watch out for messages like "Takeoff detected" or "land detected" in QGC?

I would guess that the problem is that landing is not detected (yet) in which case RTL is triggered.

**Comment by ender-chen** [comment] 2016-05-31 07:50
OK, Tomorrow I will test it again. I think I have lost logs.

**Comment by julianoes** [comment] 2016-07-13 17:37
Fixed in #4559.

**Closed by julianoes** 2016-07-13 17:37 UTC
