### ISSUE TITLE
Here 2 compass not working?

### ISSUE THREAD

**Issue by RomanBapst** [PX4/Firmware#11830] opened 2019-04-10 15:22 UTC
Tested with Pixhawk cube and latest master.

**Comment by RomanBapst** [comment] 2019-04-10 15:23
In then went on and tied with a here 1 GPS which worked.
But then I noticed that the external compass was MAG_3 and QGC did not show the option to set an external mag rotation.

**Comment by julianoes** [comment] 2019-04-11 13:27
I think this is a duplicate of #11230.

**Comment by dagar** [comment] 2019-04-11 13:44
Fixed in https://github.com/PX4/Firmware/pull/11837

**Comment by dagar** [comment] 2019-04-11 13:45
> But then I noticed that the external compass was MAG_3 and QGC did not show the option to set an external mag rotation.

Likely fixed by https://github.com/PX4/Firmware/pull/11838

**Comment by dagar** [comment] 2019-04-11 17:30
Support for the compass in the Here 2 GPS is now in master.https://github.com/PX4/Firmware/commit/95a0803b149770b8d1a5817611cd55e43a4ad296

**Closed by dagar** 2019-04-11 17:30 UTC
Labels: bug
