### ISSUE TITLE
Mavlink publishing of current repeat count of a MAV_CMD_DO_JUMP

### ISSUE THREAD

**Issue by sanderux** [PX4/Firmware#7130] opened 2017-04-26 00:02 UTC
Before any GCS can integrate or display this information it needs to be published.
I dont think this information is currently available or supported in the mavlink protocol

**Comment by dagar** [comment] 2017-04-27 04:50
https://github.com/PX4/Firmware/issues/3874

**Comment by dagar** [comment] 2017-05-02 16:36
Closing as duplicate of https://github.com/PX4/Firmware/issues/3874.

**Closed by dagar** 2017-05-02 16:36 UTC
Labels: devcall, enhancement
