### ISSUE TITLE
broken paths in rc.vehicle_setup

### ISSUE THREAD

**Issue by yashom7** [PX4/Firmware#15806] opened 2020-09-24 09:41 UTC
`make px4_sitl jmavsim `
results in a successful build but cannont load mixers and throws the error
```
/build/px4_sitl_default/tmp/rootfs/etc/init.d/rc.vehicle_setup: line 81: /etc/init.d/rc.interface: No such file or directory
ERROR [px4] Startup script returned with return value: 256
```
The files exist and I can fix the error by replacing the path in line 81 of rc.vehicle_setup
`source /etc/init.d/rc.interface`
with an absolute path like so

`source /Users/yashomdighe/Developer/PX4/Firmware/build/px4_sitl_default/tmp/rootfs/etc/init.d/rc.interface`

**Comment by julianoes** [comment] 2020-09-24 12:13
Thanks, duplicate of #15795.

**Closed by julianoes** 2020-09-24 12:13 UTC
