### ISSUE TITLE
FMUv4 motors begin spinning at start of arming tone instead of at end of tone.

### ISSUE THREAD

**Issue by kd0aij** [PX4/Firmware#3375] opened 2015-12-19 04:37 UTC

**Comment by LorenzMeier** [comment] 2016-01-01 13:31
I've assigned this to yourself. There are two potential root causes:

  * A too high DISARMED PWM or MIN_PWM setting
  * An error in the ramp logic


The offending code is somewhere here:
https://github.com/PX4/Firmware/blob/master/src/drivers/px4fmu/fmu.cpp#L771-L773

Most likely the ramp doesn't get triggered correctly. You can use printfs / warnx there since the driver is not running in interrupt context.

**Comment by kd0aij** [comment] 2016-01-02 00:43
additional observation: motors start at end of tone on first arming event after reboot, but at beginning of tone on subsequent arming events

**Comment by LorenzMeier** [comment] 2016-01-02 00:51
So you just need to check why the state doesn't get reset on disarm.

**Comment by kd0aij** [comment] 2016-01-03 15:02
[pwm_limit_state_machine.pdf](https://github.com/PX4/Firmware/files/76633/pwm_limit_state_machine.pdf)

**Comment by LorenzMeier** [comment] 2016-01-03 15:51
Nice! Could you add that to the dev guide? It supports diagrams, in this format:

```
```mermaid
graph LR;
  Gazebo-->Plugin;
  Plugin-->MAVLink;
  MAVLink-->SITL;
```
```

http://knsv.github.io/mermaid/#usage

**Comment by LorenzMeier** [comment] 2016-01-03 15:53
Example here: https://raw.githubusercontent.com/PX4/Devguide/master/book/simulation-gazebo.md

**Comment by kd0aij** [comment] 2016-01-04 19:59
fmu was asserting both armed and pre_armed inputs to pwm_limit_calc even when !_armed.armed
mermaid doesn't seem to render properly in Chromium or Firefox

**Comment by LorenzMeier** [comment] 2016-01-04 20:21
Have you fixed that in your PR accordingly? All works now?

**Comment by kd0aij** [comment] 2016-01-04 20:25
yes, just commented the PR...

**Closed** 2016-01-06 09:02 UTC
Labels: enhancement
