### ISSUE TITLE
Radio not recognized on master. Spektrum DX7 and SPM9645 Spektrum DSMX Receiver

### ISSUE THREAD

**Issue by PolskaPole** [PX4/Firmware#5300] opened 2016-08-11 19:48 UTC
Hey folks, 
Hope some of you can help me. 
As the title indicates I'm using this setup with just the Snapdragon Flight Kit, no pixhawkpixfalcon in between. 
The receiver is plugged into J15 on the board and started with `rc_receiver start -D /dev/tty-1` in the px4.config. 
I was using an old commit of this Firmware (~June 5, 2016) and it works perfectly with this setup. Now I wanted to get the latest Firmware running on it, so I flashed the latest adsp image from intrinsyc and pulled the latest PX4 Firmware and build it . Everything went fine, but when I check the Radio tab in  QGC, it has no connection to the radio. (Transmitter and Receiver are linked!) 
Has anybody else encountered this problem ? 
I'm not sure if it has something to do with the "HexagonFCAddon" part that was introduced on commits newer to my old and working commit. 

Thanks in advance!

**Comment by LorenzMeier** [comment] 2016-10-23 18:00
Duplicate of #5535.

**Closed by LorenzMeier** 2016-10-23 18:00 UTC
