### ISSUE TITLE
Wind estimator don't compute correctly

### ISSUE THREAD

**Issue by moreba1** [PX4/Firmware#15508] opened 2020-08-07 09:16 UTC
Hi

In my recent test, i see 30-degree sideslip angle during cruise with about 19 m/s airspeed but wind speed is 3.7 m/s ,
estimated wind must be about 9.5 m/s.

https://review.px4.io/plot_app?log=b7e0e58f-ee70-423c-a51e-3c583a4eb009

![sd](https://user-images.githubusercontent.com/14200369/89630182-3c8fee80-d8b4-11ea-9926-cf8900464d96.JPG)

**Comment by bresch** [comment] 2020-08-07 09:21
FYI @RomanBapst

**Comment by bresch** [comment] 2020-08-07 09:30
@moreba1 I don't think this is a wind estimator issue, the sideslip you see does not seem to be caused by the crosswind: the ground and airspeed have similar values during the whole survey, this is impossible with a wind of 9m/s.
![2020-08-07_11-26-52_01_plot](https://user-images.githubusercontent.com/14822839/89631447-12810100-d8a1-11ea-8c31-c45926a2fe40.png)

**Comment by moreba1** [comment] 2020-08-07 09:51
> @moreba1 I don't think this is a wind estimator issue, the sideslip you see does not seem to be caused by the crosswind: the ground and airspeed have similar values during the whole survey, this is impossible with a wind of 9m/s.

airspeed and ground speed can be the same value but we have wind speed because they are vector.

![image](https://user-images.githubusercontent.com/14200369/89633540-3c462200-d8b9-11ea-81b0-b1010ab245e1.png)

**Comment by Jaeyoung-Lim** [comment] 2020-08-10 08:02
@moreba1 which release are you running? previously airspeed sensor was not simulating effects of wind. 

Also, some relevant issues from @ThomasRigi in https://github.com/PX4/sitl_gazebo/pull/557

**Comment by moreba1** [comment] 2020-08-10 08:21
> @moreba1 which release are you running? previously airspeed sensor was not simulating effects of wind.

version 1.10 latest stable version

**Comment by bresch** [comment] 2020-08-10 09:02
> Airspeed and ground speed can be the same value but we have wind speed because they are vector.

Yes, but it your mission, you flew in all directions and none of them is showing a difference of more than 4-5 m/s between ground and air speed. Are you sure that the plane was really crabbing?

Furthermore, if you check the 3d replay of your log (https://review.px4.io/3d?log=b7e0e58f-ee70-423c-a51e-3c583a4eb009), you can see that the yaw offset isn't consistent when going N-W and S-E:
![Screen Capture_select-area_20200810105836](https://user-images.githubusercontent.com/14822839/89766714-e364cc80-daf8-11ea-8a0e-f011d9079beb.png)
![Screen Capture_select-area_20200810105818](https://user-images.githubusercontent.com/14822839/89766717-e5c72680-daf8-11ea-9301-6f7c90c239d2.png)
So we have heading issues and NOT wind estimator issues.

**Comment by bresch** [comment] 2020-08-10 09:06
@moreba1 Closing as this is most likely an issue with your setup and not the firmware. Please go to http://discuss.px4.io and if you find that the issue is not from you setup but from the estimator itself, please report to https://github.com/PX4/ecl

**Closed by bresch** 2020-08-10 09:06 UTC
Labels: ekf2, fixedwing, vtol

**Comment by moreba1** [comment] 2020-08-10 10:59
> 
> 
> > Airspeed and ground speed can be the same value but we have wind speed because they are vector.
> 
> Yes, but it your mission, you flew in all directions and none of them is showing a difference of more than 4-5 m/s between ground and air speed. Are you sure that the plane was really crabbing?
> 
> Furthermore, if you check the 3d replay of your log (https://review.px4.io/3d?log=b7e0e58f-ee70-423c-a51e-3c583a4eb009), you can see that the yaw offset isn't consistent when going N-W and S-E:
> ![Screen Capture_select-area_20200810105836](https://user-images.githubusercontent.com/14822839/89766714-e364cc80-daf8-11ea-8a0e-f011d9079beb.png)
> ![Screen Capture_select-area_20200810105818](https://user-images.githubusercontent.com/14822839/89766717-e5c72680-daf8-11ea-9301-6f7c90c239d2.png)
> So we have heading issues and NOT wind estimator issues.

does not wind estimator use heading of the plane ? so how sideslip angle calculated?
