### ISSUE TITLE
Gazebo SITL broken

### ISSUE THREAD

**Issue by crzx5** [PX4/Firmware#3990] opened 2016-03-11 23:10 UTC
Iris model takes off, then immediately crashes.

**Comment by locustcox** [comment] 2016-03-11 23:49
+1. To replicate:

First run make posix_sitl_default gazebo
Then, type "commander takeoff"
The quadrotor will shoot up into the sky, fall back down, bounce, and repeat a few times before finally flipping over.

**Comment by LorenzMeier** [comment] 2016-03-12 08:08
Duplicate of #3983, closing.

**Closed by LorenzMeier** 2016-03-12 08:08 UTC
