### ISSUE TITLE
Unfiltered IMU data for apps outside Firmware

### ISSUE THREAD

**Issue by ChristophTobler** [PX4/Firmware#8592] opened 2018-01-05 10:48 UTC
There's currently no proper solution to get unfiltered IMU data outside the Firmware.
https://github.com/PX4/Firmware/pull/8591 is an example hack for the Snapdragon Flight.

Ideas:
- Create new message for unfiltered data (using floats)
- Drivers publish unfiltered data and the consumer have to filter according their needs

**Comment by MaEtUgR** [comment] 2018-01-08 16:38
The three cases for which I see raw a IMU raw data output requirement reoccuring:
- debugging (where maybe logging would be enough)
- research projects that deal/prototype with IMU data but want to run "offboard"
- existing algorithms which are designed to directly consume the raw data and cannot work with processed state estimates

VISLAM looks like it is the last case. So the feature even though it's probably not for a huge audience probably makes sense to simplify developement.

**Comment by dagar** [comment] 2018-10-03 13:59
@ChristophTobler could you expand on your requirements?

Are delta angles and delta velocities desired?
At what rate?

**Comment by mhkabir** [comment] 2018-10-03 14:01
This is a duplicate of https://github.com/PX4/Firmware/issues/9796. Closing in favour of that.

**Closed by mhkabir** 2018-10-03 14:01 UTC
