### ISSUE TITLE
No PWM in standby though param is set

### ISSUE THREAD

**Issue by friekopter** [PX4/Firmware#1898] opened 2015-03-09 14:42 UTC
Though configuration introduced in  #1446 is still in place, pwm signal in disarmed mode is not sent any more.

# Provide ESC a constant 1000 us pulse while disarmed
set PWM_OUT 4
set PWM_DISARMED 1000

**Comment by friekopter** [comment] 2015-03-13 21:44
Looks like 653b3e71be7059707a0963e15dfb12e5403025aa breaks this.

**Comment by LorenzMeier** [comment] 2015-03-15 17:14
Thanks for narrowing this down. But there are more commits in that series. Could you have a look at pwm.c and see if you can resolve it for your case? The diff shows you which lines to look at, and it should be fairly easy with a few printf / warnx() statements.

**Comment by friekopter** [comment] 2015-03-15 18:31
Try to do that, but currently I am not sure any more if this change produced the effect I have. Reverting that change does not always fix my problem, it is somehow undeterministic :-(

Date: Sun, 15 Mar 2015 10:14:56 -0700

**Comment by tumbili** [comment] 2015-04-09 08:18
@LorenzMeier Is there some kind of timeout for the disarmed pwm value? When I reboot the Pixhawk I can measure the disarmed pwm pulse but after a minute or so I can't measure it anymore. Then if I do "pwm test -c 1 -p 1500" I can measure the disarmed pwm value again.

**Comment by LorenzMeier** [comment] 2015-04-09 08:21
There shouldn't be a timeout, if there is one its something we have to investigate.

**Comment by tumbili** [comment] 2015-04-09 08:56
@LorenzMeier Sorry, I had "armed" mistaken with "safety off". If safety is off I don't get the timeout.

**Comment by friekopter** [comment] 2015-04-12 16:13
In my case the problem is gone with newest checkout from master.

**Comment by tumbili** [comment] 2015-04-19 20:50
One issue was found to be related to the attitude_controller_ekf module. At some point it stopped sending attitude messages which lead to the PX4IO claiming FMU_FAIL. In my case the attitude estimator was provided with a zero mag vector which eventually lead to a NaN in the attitude estimate. I think the problem with the zero mag vector was fixed in (3658bf8). I could not reproduce the problem with ekf_att_pos_estimator.

**Comment by tumbili** [comment] 2015-04-29 13:59
I think this can be closed.

**Closed** 2015-05-13 14:53 UTC
Labels: testflights_multicopter
