### ISSUE TITLE
VTOL: Kill switch not working during aborted back transiton

### ISSUE THREAD

**Issue by sfuhrer** [PX4/Firmware#12879] opened 2019-09-02 17:41 UTC
Flipping the killswitch during an aborted front transition doesn't seem to work. 

To reproduce:
- flip transition switch (to FW)
- flip transition switch back (fo MC)
- flip kill switch

The MC motors are correctly switched off, the FW pusher isn't. It keeps spinning, even after disarm. Only switches off when moved again into FW mode and killed there. 

![image](https://user-images.githubusercontent.com/26798987/64128892-3991a180-cdb9-11e9-8428-1b4338f3e866.png)

**Comment by dagar** [comment] 2019-09-02 18:15
Likely fixed by https://github.com/PX4/Firmware/pull/12838.

The problem is that FW actuator control outputs (VTOL) were only being published on FW actuator control updates (from fw_att_control). The goal was to minimize some of the redundant mixing effort, but it's obviously wrong in various edge cases (in retrospect).

**Comment by sfuhrer** [comment] 2019-09-03 08:03
Yes fixed with #12838. Thanks @dagar ! (https://github.com/PX4/Firmware/issues/12877 is still valid though)

**Closed** 2019-09-03 08:03 UTC
Labels: bug, vtol
