### ISSUE TITLE
New feature requested, single motor run/check, to find out if m1 -m8 are connected properly

### ISSUE THREAD

**Issue by JPluess** [PX4/Firmware#4955] opened 2016-07-01 08:15 UTC
Hi dear developers,

i have just set up a drone with the tarot zyx-m controller, i see they have a nice tool that can spin each motor, this way it is easy to identify if al motors are connected properly.
sometimes wiring is hidden, this would be of much help.

![bild 1ssssss](https://cloud.githubusercontent.com/assets/7995240/16515843/be1b4054-3f74-11e6-95c7-16b70a4cc158.png)

press m1 -> m1 will spin slowly for 5 sec.

thanks a lot

**Comment by julianoes** [comment] 2016-07-07 13:22
There is one command line tool to do just this, however it's not as easy as the thing on the screenshot.

Remove the SD card from the Pixhawk and connect over USB. Open a serial console and you should get to the `nsh>`. At this point, press the safety switch, so it double-blinks.

Then type:
```
pwm arm
```

And to test one channel, do:
```
pwm test -c 1 -p 1300
```
where 1300 is your PWM value and 1 is your channel counting from 1.
Also see the docs here: https://pixhawk.org/firmware/apps/pwm

**Comment by dagar** [comment] 2016-07-07 15:42
I opened a pull request to move MAV_CMD_DO_MOTOR_TEST into common. Don was interested in adding this QGC.

https://github.com/mavlink/mavlink/pull/580

**Comment by dagar** [comment] 2016-07-07 15:43
Would it make sense to modify motor_ramp to do this? Plus something to temporarily disable the controllers.

**Comment by dagar** [comment] 2016-07-10 22:42
https://github.com/PX4/Firmware/issues/5023

**Comment by LorenzMeier** [comment] 2016-07-11 21:04
I'm closing the feature request in favour of the issue discussing how we will implement it.

**Comment by dagar** [comment] 2019-01-21 01:10
Duplicate of https://github.com/PX4/Firmware/issues/10782

**Closed by dagar** 2019-01-21 01:10 UTC
Labels: enhancement
