### ISSUE TITLE
Airspeed sensor issue

### ISSUE THREAD

**Issue by tumbili** [PX4/Firmware#2776] opened 2015-08-28 08:24 UTC
This is a log showing complete failure of the airspeed sensor. The airspeed sensor has been calibrated before and was indicating values when blowing into it on the ground.
Log: http://dash.oznet.ch/view/pFDAKzzFivKPvwXwqtwwGK

**Comment by LorenzMeier** [comment] 2015-11-17 11:40
Duplicate of #2729.

**Closed by LorenzMeier** 2015-11-17 11:40 UTC
