### ISSUE TITLE
Wrong version displayed (or flashed)

### ISSUE THREAD

**Issue by vvranjek** [PX4/Firmware#7391] opened 2017-06-09 18:49 UTC
I flashed (presumibly) v1.6.2 using qGroundControl-3.1.3, but `ver all` says I have v1.6.1.

```
nsh> [Kver all
HW arch: PX4FMU_V2
FW git-hash: 50ecee9df817ebc414d606b5b551aab08d86b598
FW version: 1.6.1 0 (17170688)
OS: NuttX
OS version: Release 7.10.0 (118489343)
OS git-hash: 8b81cf5c7ece0c228eaaea3e9d8e667fc4d21a06
Build datetime: Jun  8 2017 13:24:52
Build uri: localhost
Toolchain: GNU GCC, 5.4.1 20160919 (release) [ARM/embedded-5-branch revision 240496]
MFGUID: 313235333432470b00260038
MCU: STM32F42x, rev. A

WARNING   WARNING   WARNING!
Revision A has a silicon errata:
This device can only utilize a maximum of 1MB flash safely!
https://pixhawk.org/help/errata
```

**Comment by dagar** [comment] 2017-06-09 19:17
Duplicate of this issue - https://github.com/PX4/Firmware/issues/7378

**Closed by dagar** 2017-06-09 19:17 UTC
