### ISSUE TITLE
UAVCAN ESC don't seem to respond the way they should

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#6796] opened 2017-03-12 20:31 UTC
http://logs.px4.io/plot_app?log=155832f2-b37e-44ae-a81e-fb9c8dd5de02

![screen shot 2017-03-12 at 21 11 54](https://cloud.githubusercontent.com/assets/5750020/23835588/55e519ec-076a-11e7-8c20-6f393051fda3.png)

Using: https://github.com/PX4/Firmware/pull/6795

This log shows a VTOL flight where the vehicle lost attitude and height control after the back transition. Observations:
- power consumption of the whole system is very low after the back transition even though the thrust setpoint goes to full
- the feedback from the ESCs suggest they are doing something but also that for example one motor is still turned off
- attitude tracking and performance in general is fine at takeoff and before the front transition
- the UAVCAN ESC status is shifted in time and logged ~2 seconds too early (or the rest too late)

**Comment by LorenzMeier** [comment] 2017-03-12 20:57
Were you flying with Sapog or PX4esc? Those are two different codebases. It seems like Sapog might have had spinup issues:

https://github.com/PX4/sapog/pull/22

**Comment by LorenzMeier** [comment] 2017-03-12 20:59
@pavel-kirienko Can you chime in?

**Comment by AndreasAntener** [comment] 2017-03-12 20:59
Hm, not sure, the quad setup from Michael/Mathieu?
This happened now twice in flight, but never on the bench (did 10 bench tests at least today)

**Comment by LorenzMeier** [comment] 2017-03-12 21:01
The quad setup is Sapog. Can you upgrade them and re-test? I would not be surprised at all if this is related.

**Comment by LorenzMeier** [comment] 2017-03-12 21:01
And do you have bandwidth to look into the logging issue?

**Comment by AndreasAntener** [comment] 2017-03-12 21:01
> - can pick up synchronization if the rotor is already rotating.
>
> Significantly more reliable operation during rapid acceleration and deceleration, especially at high advance angles.

Well that sounds very suspicious..

**Comment by pavel-kirienko** [comment] 2017-03-12 21:01
@AndreasAntener Is it true that you were restarting the motors in flight (this is what I'm reading from the plots)? If so, then indeed, it could be caused by the spinup issues I've been fixing in the last few days. You might find the new beta to perform noticeably better.

**Comment by AndreasAntener** [comment] 2017-03-12 21:01
Michael and I figured out the logging issue today, fix incoming.

**Comment by AndreasAntener** [comment] 2017-03-12 21:02
Sorry my bad, I guess you mean the timing issue, no not that (but the multi instance problem which is not logging related)

**Comment by AndreasAntener** [comment] 2017-03-12 21:03
@pavel-kirienko yes that is true. Which would explain why we cannot reproduce it on the bench. What's the easiest to upgrade (sorry I'm a UAVCAN newbie here)

**Comment by pavel-kirienko** [comment] 2017-03-12 21:08
@AndreasAntener this should help: https://dev.px4.io/uavcan-node-firmware.html#firmware-installation-on-the-autopilot

**Comment by AndreasAntener** [comment] 2017-03-12 21:43
Thanks. Stupid question: what hardware version do I have? :)

**Comment by pavel-kirienko** [comment] 2017-03-12 21:46
You have v1.0 I guess.

**Comment by pavel-kirienko** [comment] 2017-04-24 22:20
@AndreasAntener fixed in https://github.com/PX4/sapog/pull/22. Version 2.0 should be officially released before the end of the week.

**Comment by pavel-kirienko** [comment] 2017-04-26 16:02
Should we close it, or is anybody willing to volunteer and test it? My own tests indicate that the issue is fixed. @mhkabir @AndreasAntener please advice.

**Comment by mhkabir** [comment] 2017-04-26 16:05
@eyeam3 Will be testing the latest Sapog release within the next few days.

**Comment by bresch** [comment] 2017-06-07 14:08
@pavel-kirienko @AndreasAntener Tested today with Orel20 and Sapog v2.2. I first tried if my drone was able to recover from a free-fall and then I tried to flip the kill switch during ~0.5s. The motors were able to restart successfully.

[Video](https://drive.google.com/open?id=0B0uX_2YN9jiNeUVNbU1OVENfVm8) of the kill switch flip sequence and complete [log](http://logs.px4.io/plot_app?log=6c80a1d7-6127-4948-a0f3-c65e92b86bcb).

Below, the graph of the current consumption of each ESC:
![orel20_restart_current](https://user-images.githubusercontent.com/14822839/26882643-3fb74490-4b9b-11e7-8e5e-1120dec7152c.png)

**Closed by bresch** 2017-06-07 14:08 UTC
Labels: bug

**Comment by pavel-kirienko** [comment] 2017-06-07 15:06
Thanks, Mathieu.
