### ISSUE TITLE
Drift when estimating attitude on Snapdragon eagle platform

### ISSUE THREAD

**Issue by ericye16** [PX4/Firmware#5110] opened 2016-07-20 20:19 UTC
Hi,
I'm noticing drift / poor attitude estimation on the Snapdragon eagle platform. For example, if I flip the drone on its back, it takes a few seconds to settle and find the correct attitude. Similarly when I flip it back, the roll angle will be wrong by up to 45 degrees and only slowly correct. What parameters can I tune to fix this? I've already tried changing parameters in Attitude Q estimator via QGroundControl but these changes don't seem to affect it.
EDIT: it actually uses the ekf2 estimator on the qurt side despite SYS_MC_EST_GROUP. So ekf2 seems to be drifting.

**Comment by julianoes** [comment] 2016-07-22 16:05
If the angle is wrong by about 45 degrees I would say that the gyro scaling is off by a factor of 2. However, I can't reproduce the issues with my Snappy.

Can you try with q/inav and check the performance?

Change `posix-configs/eagle/flight/px4.config` and replace:
```
ekf2 start
```
with
```
attitude_estimator_q start
position_estimator_inav start
```

and do `make eagle_default upload`.

**Comment by ericye16** [comment] 2016-07-22 17:09
Should I be building with eagle_legacy_default or eagle_default? I've been using legacy_default this whole time...

**Comment by julianoes** [comment] 2016-07-22 17:27
You can try what works better for you. I don't really know. Legacy uses the proprietary Qualcomm drivers and default the open-source DriverFramework drivers, as far as I know.

**Comment by ericye16** [comment] 2016-07-22 17:54
Replacing the ekf2 estimator with the attitude_estimator_q and position_estimator_inav does fix it. If it were the gyro scaling problem, where should I look to start debugging it? in the ekf2 module or lower (like at the drivers?)

**Comment by julianoes** [comment] 2016-07-22 17:57
If it were a gyro scaling issue, it would be in the driver.

**Comment by ericye16** [comment] 2016-07-22 18:05
Wait, wouldn't a gyro scaling issue in the driver also affect attitude_estimator_q or position_estimator_inav as well?

**Comment by julianoes** [comment] 2016-07-22 18:23
Correct, that's why I'm assuming there is no problem. If the ekf2 doesn't behave, there might be another issue there (maybe related to Snapdragon). I'll do more testing/test flying soon.

**Comment by ericye16** [comment] 2016-07-22 20:43
Here are some gifs to help you out.
![Uploading VID_20160722_113351.gif…](attitude_estimator_q and position_estimator_inav
![Uploading VID_20160722_113458.gif…](ekf2)
)

I know the quality is terrible but hopefully you can see that the horizon "lags" in the ekf2 video.

**Comment by mhkabir** [comment] 2016-07-23 06:06
That version of QGroundcontrol is prehistoric!

**Comment by julianoes** [comment] 2016-07-23 07:44
@ericye16 Thanks for the videos, that's very helpful. I just want to try to understand which drivers exactly you are running.

Can you please share the output of:

```
adb shell "cat /home/linaro/mainapp.config"
adb shell "cat /usr/share/data/adsp/px4.config"
```

**Comment by julianoes** [comment] 2016-07-23 07:54
@ericye16 nevermind, I can reproduce your issue. Looking into it.

**Comment by julianoes** [comment] 2016-07-23 12:26
@ericye16 I have a potential fix.

Can you cross-test https://github.com/PX4/DriverFramework/pull/132 please?

**Comment by ericye16** [comment] 2016-07-24 20:39
Sure, I'll test it out tomorrow (Monday) at the office.

**Comment by ericye16** [comment] 2016-07-25 16:55
Checked it out and it works great now! Thanks a bunch. :shipit:

**Comment by julianoes** [comment] 2016-07-25 18:36
Cool, I'll get it to master tomorrow then.

**Comment by julianoes** [comment] 2016-07-26 15:11
https://github.com/PX4/DriverFramework/pull/132 is merged, closing.

**Closed by julianoes** 2016-07-26 15:11 UTC
Labels: bug, snapdragon
