### ISSUE TITLE
PX4 ver 1.8 control lost & unexpected behaviour

### ISSUE THREAD

**Issue by albert21martins** [PX4/Firmware#9845] opened 2018-07-06 08:00 UTC
Hi,

By performing a survey, the copter went unstable at aprox. minute 6, we lost control, but thanks to geofance  could be saved. After reviewing the log, we cannot say what went wrong. Our internal logs show that the motor 8 started abnormal behaviour at min 4 and broken at min 5. 
![image](https://user-images.githubusercontent.com/15032533/42366868-9cd44f90-8102-11e8-8619-cb89e7b002cf.png)

Log here:
https://logs.px4.io/plot_app?log=dd3c8aa9-9d77-428d-8054-ce055f5ec0ef

The system is:
- Octocopter coax, up to 5 Kg
- Pixhawk 2.1, ver 1.8
- Here GPS & 3DR GPS for magnetometer and secondary GPS, as there is nor driver implemented yet for HERE GPS. Btw, the 3DR GPS should be set 180º magnetometer orientation in order to work (bug here?).

Does anybody has any idea what could be the source of our problem?

Sincerely,

Albert

**Comment by LorenzMeier** [comment] 2018-07-06 09:29
Looks like a mechanical or electrical problem. The difference in outputs is a tell-tale sign.

**Comment by kuiskas** [comment] 2018-07-06 12:21
Hi Lorenz,

thanks for the fast answer. We also have a custom board as Power supply 1, and the standard from the Pixhawk 2 cube as a secondary Supply. I realized the Power supply 1 is not working anymore. Could this somehow perform a brownout in the system and perform a reboot? What happens if the system restart while flying?

**Comment by LorenzMeier** [comment] 2018-07-06 13:13
You can check in the flight log with a tool called Flight Plot. But its not the root cause, because the log file continued and you clearly have an issue with your actuators.

I'm closing this because its not an issue with the upstream software but with your specific airframe. Feel free to post on http://discuss.px4.io for community support or alternatively contact one of the consulting companies which offer commercial support.

**Closed by LorenzMeier** 2018-07-06 13:13 UTC
