### ISSUE TITLE
Change Altitude causes yaw setpoint change

### ISSUE THREAD

**Issue by jianyang1** [PX4/Firmware#7638] opened 2017-07-18 09:20 UTC
when loitering after reposition, changing the altitude will cause 180 deg change in yaw sp (facing the previous position)
 (FW v1.6.5 QG 3.2.0)

1. Take-off
2. re-position 100m north
3. when loitering after reaching the point- change altitude to 50m
4. bug- the drone changes the yaw setpoint (facing south)

http://review.px4.io/plot_app?log=a6cbe484-4ef9-46b4-91f2-f98e3708d407

**Comment by TSC21** [comment] 2017-07-18 09:23
Oh that's funny, as I'm getting the same behavior on SITL Gazebo. Maybe a different issue but totally worth to investigate. What's your vehicle setup?

**Comment by BazookaJoe1900** [comment] 2017-08-11 14:42
@LorenzMeier don't you think that this issue is priority?

**Comment by VineeshKK** [comment] 2017-09-04 08:45
Not able to replicate this issue. Tried to replicate it on Gazebo ver 7.8.1,  FW ver: 1.6.5 0 . QGC lateste ver.
This was the observation.
Initially Drone was directed towards East, then  it took off to 100m
After take-off , flew the drone towards 100m North.  (so the drone was directed towards North).
Loiter for 5 seconds once it reached 100m North.
Then reduced the altitude to 50m. 
I was still able to see the Drone directed towards North. which is expected
Did I miss any steps here?

**Comment by jianyang1** [comment] 2017-09-04 13:28
try start the maneuver in your takeoff altitude, then after flying north, climb to about 50 m.
i am still witness this behavior, in various maneuvers and altitudes, though it's not happening in **every** altitude change.
not sure whats trigger it but it is still happens pretty oftenly

**Comment by BazookaJoe1900** [comment] 2018-02-17 16:01
Any news about this issue?

**Comment by dagar** [comment] 2018-02-17 16:10
Please continue posting logs if you see this issue.

**Comment by Stich123** [comment] 2018-02-22 14:27
I have the same issue v1.7.3 QG 2.7.0
https://review.px4.io/plot_app?log=e1b133ba-a994-4aa6-868f-6893b505554f

**Comment by RomanBapst** [comment] 2018-03-16 09:23
I debugged this issue and found where the problem is and when the problem occurs.

The problem happens if you demand and altitude change if the vehicle has overshot the current position setpoint. As a result the navigator will calculate a new yaw setpoint which in that case is about 180 degrees off.
This is where the magic happens, as you can see there is a magic threshold of 1m.
https://github.com/PX4/Firmware/blob/master/src/modules/navigator/loiter.cpp#L150

@LorenzMeier once committed a fix to help with this https://github.com/PX4/Firmware/commit/e1e15add01bf9292bd636581037a8673b376af15

In the end in depends on vehicle tuning and the value of the magic threshold.

**Comment by RomanBapst** [comment] 2018-03-20 09:36
I'm closing this since this behavior is not really a bug but rather an effect of the position controller excessively overshooting the position setpoint (the threshold is set to 1 m).

**Closed by RomanBapst** 2018-03-20 09:36 UTC
Labels: bug, multicopter, offboard
