### ISSUE TITLE
Durandal: manual logger start fails

### ISSUE THREAD

**Issue by mhkabir** [PX4/Firmware#13483] opened 2019-11-15 15:24 UTC
Starting logger on Durandal (`stm32h7_support` branch) manually from Mavlink console seems to fail:

![image](https://user-images.githubusercontent.com/5557676/68954346-da291800-0791-11ea-9dde-de61bc319d64.png)

It does report that a new log file was opened, after `logger on`:
![image](https://user-images.githubusercontent.com/5557676/68954439-ffb62180-0791-11ea-8ae6-95dbbb94143c.png)

However these files are always empty:

![image](https://user-images.githubusercontent.com/5557676/68954461-0e9cd400-0792-11ea-803b-420cd1aaaafa.png)

**Comment by dagar** [comment] 2019-11-15 15:30
It seems to be working on the test rack. http://ci.px4.io:8080/blue/organizations/jenkins/PX4_misc%2FFirmware-hardware/detail/stm32h7_support/26/pipeline/661#step-840-log-5

![image](https://user-images.githubusercontent.com/84712/68954879-e06bc400-0792-11ea-99e0-751e06b83ab0.png)


![image](https://user-images.githubusercontent.com/84712/68954810-c03c0500-0792-11ea-81bb-1651793aa6d4.png)


![image](https://user-images.githubusercontent.com/84712/68954824-c631e600-0792-11ea-8558-6904d7a0f51e.png)

**Comment by davids5** [comment] 2019-11-15 16:15
@mhkabir - I think there may be a power sequencing issue with the SD.
What does dmesg show?

**Comment by LorenzMeier** [comment] 2019-11-15 16:56
@mhkabir How do you power the unit? We have flown successfully with valid logs. I presume you did start that on the bench?

@davids5 I have confirmed the power sequencing issue. Steps:

- Remove the SD card
- Unpower Durandal
- Plug USB in
- Plug the SD card in BEFORE the boot loader lights go out
- run ```logger stop && logger start -e```

**Comment by LorenzMeier** [comment] 2019-11-15 16:57
I would leave this issue open so we can add an errata to the documentation @hamishwillee as a known hardware limitation if powered via USB. But it is not a software issue per se (and maybe we can work around it in SW later).

**Comment by mhkabir** [comment] 2019-11-15 18:17
Some more details:
- I'm powering via USB only.
- Logging works if it's starting from boot.
-

**Comment by mhkabir** [comment] 2019-11-15 18:18
@LorenzMeier yes, this is on bench, powered from USB only.

- I'm powering via USB only.
- Logging *does work* if it's started from boot. (SDLOG_MODE)
- I didn't touch the SD card.

**Comment by mhkabir** [comment] 2019-11-15 18:23
@davids5 
![image](https://user-images.githubusercontent.com/5557676/68966004-1b79f180-07ab-11ea-99e9-c94e9775e135.png)

**Comment by zhaoxiaowei1013** [comment] 2020-04-17 01:25
have a plan to solve it？I also encountered the same problem。

**Comment by davids5** [comment] 2020-04-17 10:30
@zhaoxiaowei1013 This was addressed in https://github.com/PX4/Firmware/pull/14592 

Please test current master and reopen this issues if it did not solve it.

**Closed by davids5** 2020-04-17 10:30 UTC
Labels: bug

**Comment by jareiko** [comment] 2020-04-21 14:33
I'm still sometimes getting what might be this problem on master, running off battery power.

At some point the SD card seems to fail, and then nothing works anymore (logging or sd_bench, for example).

![Screenshot from 2020-04-21 16-27-58](https://user-images.githubusercontent.com/764352/79878107-55e85a00-83ed-11ea-8e04-41034eee035d.png)

**Comment by dagar** [comment] 2020-04-21 15:24
@jareiko could you open a new issue for that and start collecting any relevant data?

Is that console screenshot showing anything other than logger successfully starting?

Have you noticed any patterns? Does it fail after a certain period of time? Are you getting any potentially relevant error messages from logger or the system? You could check `dmesg` output.

**Comment by jareiko** [comment] 2020-04-21 16:51
That is just a dmesg log, as requested earlier in the thread. Yes, I'll start a new issue for this when I'm looking at it again. For now we're exploring log streaming instead.

**Comment by davids5** [comment] 2020-04-21 18:32
@jareiko - Also have you tried another card?

**Comment by jareiko** [comment] 2020-04-21 20:45
Yes, three different cards, all of which work fine on a Pixhawk 4.

**Comment by zhaoxiaowei1013** [comment] 2020-04-23 02:50
This problem still exists. I tested this problem in the latest master branch
![Screenshot from 2020-04-23 10-49-20](https://user-images.githubusercontent.com/9687758/80053708-230aa700-8550-11ea-8ac9-e3f8c5fd90fb.png)
And all in my  cuav v5+ is work good.

**Comment by davids5** [comment] 2020-06-29 15:20
Resolved by https://github.com/PX4/NuttX/pull/106
