### ISSUE TITLE
FW setting invalid PWM rate

### ISSUE THREAD

**Issue by JonReacher** [PX4/Firmware#7490] opened 2017-06-27 12:52 UTC
After updating firmware through Qgroundcontrol I am experiencing severe strain/ vibrations in my elevon servos. After testing older firmwares and Ardupilot with no issues, it is only the PX4 firmware update causing this. Is there a known issue that I'm not aware of, or a change that needs to be made on my end to eliminate this?

**Comment by dagar** [comment] 2017-06-27 14:43
Can you share a log? Under what circumstances is this happening?

**Comment by JonReacher** [comment] 2017-06-27 15:10
I have a plane set up with the tbs caipirinha airframe preset. I've been using it for 6 months. It's been running 1.5.5. I updated yesterday to 1.6.3 through Qgroundcontrol firmware update and the servos immediately started grinding/vibrating/ random movements. They respond to manual input but with lag and they are still under strain the entire time, armed or not.

 I took the pixhawk out of the loop and they were fine under rc control. I switched to ardupilot firmware and they were fine. I switched back to 1.6.3 and it began having the same issues. I tried different flying wing presets and they all suffered the same. I tried setting pwm parameters to all default. No change.

**Comment by JonReacher** [comment] 2017-06-27 15:12
Can you use a .px4log?

**Comment by dagar** [comment] 2017-06-27 15:22
Logs before and after would be helpful.

**Comment by JonReacher** [comment] 2017-06-27 15:23
Here's an after: http://logs.px4.io/plot_app?log=0cce62f1-a27b-4350-afcd-293e33fd9e6b

I'll upload a before now.

**Comment by JonReacher** [comment] 2017-06-27 15:24
I should mention that it was any position on the main outputs that it occurred.

**Comment by dagar** [comment] 2017-06-27 15:28
Is this reproducible with bench testing or are you only seeing it in flight?

**Comment by dagar** [comment] 2017-06-27 15:30
I can compare your logs later, but as a quick thing can you first fully recalibrate all sensors with the new firmware?

![image](https://user-images.githubusercontent.com/84712/27595913-02a92f78-5b2c-11e7-8d35-0a1e3cda3cdb.png)

**Comment by JonReacher** [comment] 2017-06-27 15:32
Here's a plot of a flight before: http://logs.uaventure.com/view/zQfdzTjo2BVdyDDDxUZeJW#top

This was only on the bench. I would not have been able to fly in this condition. The servos were getting hot under the strain.

**Comment by JonReacher** [comment] 2017-06-27 15:34
Yeah, I did full recalibration 20 times yesterday. That log was I guess after a fresh reflash, before calibration. I'll reflash, recalibrate and create a more controlled log.

**Comment by JonReacher** [comment] 2017-06-27 15:37
One thing I notice is that on the old log I see the expected actuator channels, 0,1,2, and 3. On the new log I only see outputs 2,3, and 7.

**Comment by JonReacher** [comment] 2017-06-27 15:41
Here's a log from yesterday with calibration: http://logs.px4.io/plot_app?log=7d35482b-958d-4e45-9add-f589d62f61ea

**Comment by dagar** [comment] 2017-06-27 15:41
We need to find the disconnect between what you're experiencing and what the log shows.
Here's the PWM outputs from your first log.

![image](https://user-images.githubusercontent.com/84712/27596449-9b5fb164-5b2d-11e7-836c-9a04c40a4d9a.png)

**Comment by dagar** [comment] 2017-06-27 15:43
PWM outputs again in the 2nd log. 

![image](https://user-images.githubusercontent.com/84712/27596518-c17b32ec-5b2d-11e7-934b-ab7384af1d6f.png)

**Comment by dagar** [comment] 2017-06-27 15:46
Can you try the following to see if it makes a difference?

PWM_MIN 900 -> 1000
PWM_MAX 2100 -> 2000
PWM_RATE 400 -> 50

Have you ever connected a console? https://dev.px4.io/en/debug/system_console.html
If you can, run the command `pwm info`.

**Comment by JonReacher** [comment] 2017-06-27 16:18
Alright, I did a new flash to 1.6.3, full calibration, and created 2 logs, before and after your recommended changes. The changes did work. 
 Here is the before: http://logs.px4.io/plot_app?log=b5f158f0-c9c4-4111-9182-48a86f0c810c
 Here is after the changes: http://logs.px4.io/plot_app?log=24cc86e0-0d6b-48c4-ae45-1a4d7ed579fd

**Comment by JonReacher** [comment] 2017-06-27 16:25
I changed just the PWM_RATE back to the default of 400 and it has the issues again, so that must be it. That's probably the only relevant parameter that I didn't change yesterday.

**Comment by mhkabir** [comment] 2017-06-27 16:52
Why were you running `PWM_RATE` of 400 Hz on a plane in the first place? Standard analog servos only 50 Hz.

**Comment by JonReacher** [comment] 2017-06-27 16:59
I applied the tbs caipirinha settings to a similar airframe. I've been using this setup for a while now with no issues. I have no idea why the rate was 400HZ. I had never looked at that setting in the parameters before. Is there a reason why it would be set at that default?

**Comment by JonReacher** [comment] 2017-06-27 17:01
To me the question remains why would a 400HZ setting act differently between versions?

**Comment by mhkabir** [comment] 2017-06-27 17:05
There was a bug where the 400Hz rate wouldn't actually get applied before. It was fixed in v1.6 with the FMU app and PWM refactoring.

**Comment by JonReacher** [comment] 2017-06-27 17:10
Alright, that answers it then. Is there a way to default the rate for different classes of vehicles?

**Comment by dagar** [comment] 2017-06-27 17:12
@mhkabir the rate defaults are a bit of a mess and I think it slipped through in the past due to the rate group bug.
We need to do a pass and make sure everything is actually working as intended.
https://github.com/PX4/Firmware/issues/7261

**Closed** 2017-06-27 17:21 UTC
Labels: bug

**Comment by mhkabir** [comment] 2017-06-27 17:34
@dagar Yeah, agreed.
