### ISSUE TITLE
[TECS] Excessive pitch_sp when engaging TECS

### ISSUE THREAD

**Issue by boosfelm** [PX4/Firmware#2719] opened 2015-08-18 15:19 UTC
The issue of #2531 remains, sometimes when we go into Altitude Hold mode the ATSP_PitchSP goes to min or max value. Any idea what condition is hit by accident that it performs that way?
![screen shot 2015-08-18 at 16 56 57](https://cloud.githubusercontent.com/assets/6023217/9333510/8632abc2-45ca-11e5-814a-0b702010b63f.png)
![screen shot 2015-08-18 at 16 56 30](https://cloud.githubusercontent.com/assets/6023217/9333501/7d6749da-45ca-11e5-9f4f-d79d37784df2.png)

logs will be added as soon as the are uploaded.

**Comment by LorenzMeier** [comment] 2015-08-18 16:08
Thanks for reporting - I don't have a suspicion off the top of my head.

**Comment by LorenzMeier** [comment] 2015-08-18 16:32
Is there some way for you to repro this in HIL?

**Comment by boosfelm** [comment] 2015-08-19 10:53
here the log from the first screenshot:
http://dash.oznet.ch/view/g3JvqUdUiQpN86frZUa87i

Regarding HIL I am not sure, I will have to talk to the guys.

**Comment by tumbili** [comment] 2015-08-19 11:05
@boosfelm Are you sure this is the same log from the screenshot?

**Comment by tumbili** [comment] 2015-08-19 11:12
![tecs](https://cloud.githubusercontent.com/assets/7610489/9354819/dba38a3c-4673-11e5-9b3b-454437428311.png)

**Comment by tumbili** [comment] 2015-08-19 11:14
@boosfelm @LorenzMeier However, this log also shows interesting things. At the moment when you switch to altitude control mode the pitch setpoint goes up and from the airspeed reading you would assume the aircraft was stalling. This is probably also why you have switched out of this mode again. The altitude error at this point (not plotted) was very small, so I can't see a reason why the pitch should have gone up like crazy.

**Comment by tumbili** [comment] 2015-08-19 11:16
Notice also that the second try seemed to work well. Max, can you explain if my observation is consistent with you flight experience?

**Comment by LorenzMeier** [comment] 2015-08-19 11:29
You are just looking at the symptoms, not at the actual control action. You need to plot the TECS energy and energy allocation, in particular TER and EDR. These should start at zero on mode switching and then build up. The shared log is not plotting them correctly, here is an example from another log where they spike incorrectly:
http://dash.oznet.ch/view/MRjW8NUNYQSuSZkbn8dEjY#TECS_Inner_Loop_PLOT

**Comment by LorenzMeier** [comment] 2015-08-19 11:43
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2_messages.h#L372-L375
and
https://github.com/PX4/Firmware/blob/master/src/modules/sdlog2/sdlog2_messages.h#L548

Total energy rate = integ6_state:
https://github.com/PX4/Firmware/blob/master/src/lib/external_lgpl/tecs/tecs.cpp#L367

Energy distribution rate = integ7_state:
https://github.com/PX4/Firmware/blob/master/src/lib/external_lgpl/tecs/tecs.cpp#L454

Its pretty simple: TER is the combined altitude and speed energy. EDR is how the energy error is compensated. TERSP is the desired total energy and EDRSP is the desired distribution rate.

I have long advocated a TECS rewrite / clean new implementatoin (as in using human-readable variables, not changing any of the logic (yet)). But it has to be done cleanly (in copyright terms, so not copying the file), well tested and in BSD + Eigen so that we can base on it in the future.

**Comment by tumbili** [comment] 2015-08-19 11:49
@LorenzMeier TER is the combined altitude and speed energy RATE, no? I believe we just log the rates but not the energies.

**Comment by tumbili** [comment] 2015-08-19 21:09
@boosfelm I've flown ALTCTL, POSCTL, RTL, LOITER and AUTO today for a while. Couldn't reproduce this phenomena you mentioned. As I said, I think you shared the wrong log here. If you share the correct one I can look further into this.

**Comment by boosfelm** [comment] 2015-08-20 07:49
@tumbili Thanks for checking again.
1) It is the correct log 672s in my first plot corresponds to 88s in yours.
2) Regarding the symptoms I also agree, i.e. when we enter altitude control the Pitch_SP jumps up to max (we also experienced minimal value in another instance) and our att controller tries to follow.
3) However, I am still usnure what is causing it to happen. My guess would be some cornercase in the initialization.
![screen shot 2015-08-20 at 09 48 52](https://cloud.githubusercontent.com/assets/6023217/9378308/b9590bde-4720-11e5-8fa1-441915c318f4.png)

**Comment by LorenzMeier** [comment] 2015-08-22 18:52
This here could be a potential fix:
#2743

**Comment by LorenzMeier** [comment] 2015-08-23 12:08
Fixed on all branches according to our HIL and flight testing.

**Closed by LorenzMeier** 2015-08-23 12:08 UTC

**Comment by boosfelm** [comment] 2015-08-23 12:57
thanks for the fix! We will fligth test it next week!
