### ISSUE TITLE
Failed to Install PX4 in ROS

### ISSUE THREAD

**Issue by RizqiPangestu** [PX4/Firmware#15064] opened 2020-06-09 13:19 UTC
I'm new with this, i have tried the instruction in this link [https://dev.px4.io/v1.9.0/en/setup/dev_env_linux.html#ros](url)
and sourcing this [https://raw.githubusercontent.com/PX4/Devguide/v1.9.0/build_scripts/ubuntu_sim_ros_melodic.sh](url)

after following the installation, i found 4 packages were abandoned and 2 packages failed

![Screenshot from 2020-06-09 20-17-46](https://user-images.githubusercontent.com/45598912/84152026-55d01680-aa8e-11ea-8c57-0ac144902dc9.png)
how to solve this? help me please

**Comment by TSC21** [comment] 2020-06-09 13:27
Duplicate of https://github.com/PX4/Firmware/issues/14984. Please have a look at this issue, as the problem is related to the fact that `rosdep` doesn't get installed on the scripts, requiring an update to these.

**Closed by TSC21** 2020-06-09 13:27 UTC
