### ISSUE TITLE
Check mixer limitation

### ISSUE THREAD

**Issue by julianoes** [PX4/Firmware#3535] opened 2016-01-18 17:38 UTC
@muharred reported a possible bug in https://github.com/PX4/Firmware/blob/master/src/modules/systemlib/mixer/mixer_multirotor.cpp#L304

**Comment by LorenzMeier** [comment] 2016-03-24 10:05
I don't see what's wrong with that line - would be good to know what he thinks is broken there.

**Comment by muharred** [comment] 2016-03-24 10:31
I think the pointer was moved - should have used the commit-specific pointer. The problem is with the line bellow: https://github.com/PX4/Firmware/blob/791ec37f43635947dbe99e43b746144f30f1e442/src/modules/systemlib/mixer/mixer_multirotor.cpp#L310
max_out should be greater than 0.0 in all cases of positive thrust.

**Comment by LorenzMeier** [comment] 2016-03-24 10:59
Do you have a proposed fix?

**Comment by muharred** [comment] 2016-03-24 11:01
Well, I think `max_out > 1.0f` was intended and 0.0f got there as a copy-pase error.

**Comment by LorenzMeier** [comment] 2016-03-24 11:07
Yep. Fixed in 76a8bea.

**Closed by LorenzMeier** 2016-03-24 11:07 UTC
Labels: bug, multicopter
