### ISSUE TITLE
ALTITUDE.altitude_relative value incorrect

### ISSUE THREAD

**Issue by DonLakeFlyer** [PX4/Firmware#6165] opened 2016-12-24 13:52 UTC
Running SITL on a master from yesterday. You can see the problem in the mavlink inspector screenshot. Look at the relative alt from the GPS which is correcvt, as opposed to relative alt in ALTITUDE which is incorrect:
![screen shot 2016-12-24 at 5 50 29 am](https://cloud.githubusercontent.com/assets/5876851/21467290/055f9796-c99d-11e6-82af-99d2aa2d5039.png)

**Comment by LorenzMeier** [comment] 2016-12-25 10:59
I can't reproduce this with current master, with none of the estimators in no state (home set or home not yet set):

<img width="692" alt="screen shot 2016-12-25 at 11 58 36" src="https://cloud.githubusercontent.com/assets/1208119/21470804/96c0ad90-ca99-11e6-92e7-64e9f6b5c9b5.png">
<img width="692" alt="screen shot 2016-12-25 at 11 57 55" src="https://cloud.githubusercontent.com/assets/1208119/21470805/96e87190-ca99-11e6-8b86-9107d42c5422.png">
<img width="692" alt="screen shot 2016-12-25 at 11 57 18" src="https://cloud.githubusercontent.com/assets/1208119/21470806/96e9009c-ca99-11e6-92ed-36c5699dfff0.png">
<img width="692" alt="screen shot 2016-12-25 at 11 56 59" src="https://cloud.githubusercontent.com/assets/1208119/21470807/96e953e4-ca99-11e6-81f9-6c0fa1fbcb25.png">

**Comment by LorenzMeier** [comment] 2016-12-25 11:11
Diff to debug locally:

```C++
diff --git a/src/modules/mavlink/mavlink_messages.cpp b/src/modules/mavlink/mavlink_messages.cpp
index f525f6f613..9a9570996a 100644
--- a/src/modules/mavlink/mavlink_messages.cpp
+++ b/src/modules/mavlink/mavlink_messages.cpp
@@ -3429,6 +3429,7 @@ protected:
                        } else {
                                msg.altitude_relative = NAN;
                        }
+                       PX4_INFO("alt: gp: %llu hp: %llu, rel: %f, glob: %f, home: %f", _global_pos_time, _home_time, msg.altitude_relative, global_alt, home.alt);
                }
 
                if (updated) {
```

**Comment by LorenzMeier** [comment] 2016-12-25 19:55
I can't repro but the SITL system is reproducing:
```
(vtol_new_1.txt) took too long to get to position lat:  47.397731863, lon:   8.543269296, alt:  15.00, xy off: 5.000000, z off: 5.000000, timeout: 600, index: 0, pos_d: 6.505292, alt_d: 473.084000, VTOL state: VTOL MC
```
Note the alt_d (altitude difference value) which is completely out of whack. That's because the tester and the vehicle couldn't agree on what home level is.

**Comment by LorenzMeier** [comment] 2016-12-25 20:03
@jgoppert I had it now with LPE that it would initialise at the baro altitude for home. Is this maybe the issue here?

**Comment by dagar** [comment] 2017-02-16 06:16
Duplicate https://github.com/PX4/Firmware/issues/6274?

**Comment by dagar** [comment] 2017-04-11 21:37
Fixed?

**Comment by jgoppert** [comment] 2017-04-28 16:27
Fixed on master.

**Closed by jgoppert** 2017-04-28 16:27 UTC
Labels: bug
