### ISSUE TITLE
LOCAL_POSITION_NED Cant Init After Arming

### ISSUE THREAD

**Issue by meteor0530** [PX4/Firmware#5593] opened 2016-10-04 01:11 UTC
Hi,

I recently updated the PX4 firmware through QGC 3.0.0. I used GPS for position estimate, then I used mavlink inspector to monitor the local_position_ned, and I found after I armed the FCU the position didnt initialize(x,y,z cant become 0). I used OFFBOARD to control the multicopter, then it turned over.how can I fix it?

Any help is appreciated.

**Comment by julianoes** [comment] 2016-10-11 10:20
Duplicate of #5604.

**Closed by julianoes** 2016-10-11 10:20 UTC
