### ISSUE TITLE
[MAVROS-SITL] FCU: Baro #0  Fail

### ISSUE THREAD

**Issue by weiweikong** [PX4/Firmware#6164] opened 2016-12-24 12:49 UTC
When I use the MAVROS in Gazebo with SITL, I got the following errors
```
ERROR [sensors] Baro #0 fail:  STALE!
[ERROR] [1482581789.245580261, 36636.374000000]: FCU: Baro #0 fail:  STALE!
```
but the local position is stable and I could control the vehicle in OFFBOARD mode.
Any suggestion?

**Comment by julianoes** [comment] 2016-12-24 13:24
@weiweikong thanks for reporting. I believe that's a duplicate of #6120.

**Closed by julianoes** 2016-12-24 13:24 UTC
