### ISSUE TITLE
Avoidance test failing since sitl-gazebo submodule update

### ISSUE THREAD

**Issue by baumanta** [PX4/Firmware#13123] opened 2019-10-08 12:30 UTC
Since commit
commit 91badceb274a0e5bc29061dffa6c124ae8285022
Author: TSC21 <n.marques21@hotmail.com>
Date:   Sun Oct 6 11:01:45 2019 +0100

    Update submodule sitl_gazebo to latest Sun Oct 06 11:02:54 GMT 2019

The PX4/avoidance cannot be run anymore. Gazebo does not start up without giving any error message.
Running under Ubuntu 16.04 with gazebo7

**Comment by baumanta** [comment] 2019-10-08 12:31
@TSC21 do you have any clue what could have gone wrong?

**Comment by TSC21** [comment] 2019-10-08 12:31
This was reported and being solved in https://github.com/PX4/Firmware/pull/13113. I am already following with @mrivi on this.

**Comment by baumanta** [comment] 2019-10-08 12:33
It does not seem to be that same bug, the one you refer to was caused by bumping the CI container. The one I observe is only present since the mentioned commit of the sitl_gazebo update.

**Comment by TSC21** [comment] 2019-10-08 12:35
@baumanta I don't see anything on sitl_gazebo that may cause a potential. Can you please describe what errors do you see? Have you tried to run the simulation with `gdb`?

**Comment by TSC21** [comment] 2019-10-08 12:36
Besides, all the other tests on CI using Gazebo run as they should. So this needs to be tracked to the exact usage of Gazebo for Avoidance.

**Comment by mrivi** [comment] 2019-10-08 12:40
the avoidance tests are the only tests that simulate a camera and that has numerous implications.
The problem I see is the following: a container update broke the CI tests since the vehicle isn't spawing anymore. The PR was merged in a rushed way not allowing all the people involed to look at it and the tests were disabled. A subsequent PR that updates the sitl gazebo submodules breaks the avoidance for 16.04 setups. Those CI tests are in place exactly to catch this problems!

**Comment by TSC21** [comment] 2019-10-08 12:57
So let's track them.

**Comment by baumanta** [comment] 2019-10-09 06:24
update: the bug seems to be present on 18.04 and 16.04. It seems to be a corner case in the model spawning. Models containing lidars as well as depth cameras do not work. Both elements individually seem to be fine

**Comment by mrivi** [comment] 2019-10-09 07:57
@dagar - please read my comment above

**Comment by TSC21** [comment] 2019-10-09 08:02
> update: the bug seems to be present on 18.04 and 16.04. It seems to be a corner case in the model spawning. Models containing lidars as well as depth cameras do not work. Both elements individually seem to be fine

As we spoke, I am bisecting this directly on the code blocks. This is a corner case on models that contain both lidar (and probably sonar models) together with depth camera models. The same problem does not happen when the model include just the lidar or just the depth camera. So that's why this only happens with the avoidance models. The changes on the gazebo lidar plugin may be causing this, but it's not confirmed. After the source is found, sitl_gazebo will be updated again.

**Comment by mrpollo** [comment] 2019-10-15 05:24
Was this issue resolved with #13151 ?

**Comment by mrivi** [comment] 2019-10-15 06:39
fixed by #13113

**Closed by mrivi** 2019-10-15 06:39 UTC
Labels: CI, avoidance, bug, gazebo, sitl
