### ISSUE TITLE
MS5611 on I2C PX4FMUv1

### ISSUE THREAD

**Issue by Janesak1977** [PX4/Firmware#2444] opened 2015-06-22 12:04 UTC
In file ms5611_i2c.cpp, line 165 and line 75, function name dev_ioctl in declaration and implementation of IOCTL function is not good. Name must be ioct.
MS5611 driver is not working on PX4FMUv1 (MS5611 is on I2C), because of that declaration.

**Comment by LorenzMeier** [comment] 2015-06-22 12:21
Could you send the patch for the fix? I don't understand what you exactly mean without a reference to the code changes.

**Comment by Janesak1977** [comment] 2015-06-22 12:35
Here is patched ms5611_i2c.cpp.file.
See declaration and implementation of function ioctl.

**Comment by LorenzMeier** [comment] 2015-06-22 12:49
Could you please attach the file in the Guthub web form or copy its content there? You can't attach files via email to github discussions.

**Comment by kd0aij** [comment] 2015-06-22 13:26
While the baro seems to be working on my FMUv1 running the release_v1.0.0 branch, ALTCTL does not. As soon as I switch to ALTCTL, my QAV250 climbs aggressively. Log: https://copy.com/myYzZB2oYGNPYqtt
Snapshot: 
![altctl](https://cloud.githubusercontent.com/assets/2300221/8282732/faebf0e2-18af-11e5-80b7-3e9d75e8dc62.png)

**Comment by Janesak1977** [comment] 2015-06-22 14:40
Yes, in release_v1.0.0 branch it is OK. 
Master branch declaration:
	virtual int	dev_ioctl(unsigned operation, unsigned &arg);
release_v1.0.0 branch declaration
	virtual int ioctl(unsigned operation, unsigned &arg);

**Comment by kd0aij** [comment] 2015-06-22 15:35
This (regression?) is from commit cd30b4d5caf717d77b5f5d30ba696408a6062387 by Mark Charlebois. Something to do with posix virtual devices?

**Comment by Janesak1977** [comment] 2015-06-22 16:28
Initially it is from commit https://github.com/PX4/Firmware/commit/d013ac092769f7975e540a24c5756002251248a4 by @mcharleb

**Comment by LorenzMeier** [comment] 2015-06-27 13:12
Fixed via 5e27b7b, thanks @tridge.

**Closed by LorenzMeier** 2015-06-27 13:12 UTC
