### ISSUE TITLE
Stable build never flashes px4io image

### ISSUE THREAD

**Issue by zottgrammes** [PX4/Firmware#1851] opened 2015-02-28 04:39 UTC
Branch: stable, no changes
Commit: 6d1df8f
Config: px4fmu-v2_default
HW arch: PX4FMU_V2
MCU: STM32F42x, rev. Y

Happens repeatedly. When I try to upload the latest build, my Pixhawk makes the "loading a new version of PX4 IO" sound but never completes with the "I'm done" sound.

Make command:

	make distclean && make archives && make upload -j8 px4fmu-v2_default

From NuttX shell during boot:

	nsh> [boot] Initialized SPI port 1 (SENSORS)
	[boot] Initialized SPI port 2 (RAMTRON FRAM)
	[boot] Initialized SPI port 4
	[boot] Initialized SDIO
	sercon: Registering CDC/ACM serial driver
	sercon: Successfully registered the CDC/ACM serial driver
	[i] Looking for microSD... 
	[i] microSD mounted: /fs/microsd 
	[i] Init script not found: /fs/microsd/etc/rc.txt 
	nshterm [6:70]
	param: selected parameter default file /fs/mtd_params
	[param] Loaded: /fs/mtd_params 
	[rgbled] on I2C bus 2 at 0x55 (bus: 100 KHz, max: 100 KHz)
	nsh: pca8574: command not found
	 1:   SYS_USE_IO: match
	 4011: + SYS_AUTOSTART: match
	[i] Config not found: /fs/microsd/etc/config.txt 
	px4io: check CRC failed: -22: Invalid argument
	telem> config for RC6 rejected by IO
	[px4io] default PWM output device
	px4io: failed to enable safety

Just in case, cleared all params (bc of the `telem> config for RC6 rejected by IO` error msg). Still fails.

**Comment by velocoderaptor** [comment] 2015-02-28 05:22
I think the problem is the `px4io safety_on` command.
Since it's failing, the startup script immediately exits and never gets to the part where it does a `forceupdate`.

**Comment by velocoderaptor** [comment] 2015-02-28 05:34
Ah, was able to reproduce it. I saved my previous parameters before I flashed to stable.
Loaded back 3454c42, restored all the params, and then loaded stable again.
And now I see the error again.

**Comment by velocoderaptor** [comment] 2015-02-28 06:12
Looking back, this was introduced with commit eb28aa6

**Comment by LorenzMeier** [comment] 2015-02-28 10:16
Sorry about that. I've pushed 6646e3b to fix this. I'm closing this, please let me know in case the issue persists.

**Comment by zottgrammes** [comment] 2015-03-02 22:05
Thanks. That put me past the `px4io safety_on` failure, but the bulid is still not flashing on my Pixhawk.

The `px4io_uploader.cpp` code fails to get a sync from the bootloader:

	px4io: check CRC failed: -22: Invalid argument
	[px4io] default PWM output device
	px4io: failed to enable safety
	[PX4IO] using firmware from /etc/extras/px4io-v2_default.bin
	[PX4IO] looking for bootloader
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bad sync 0xff,0xff
	[PX4IO] bootloader not responding
	px4io: check CRC failed: -22: Invalid argument
	[i] ERROR: PX4IO not found
	[i] ERROR: PX4IO not found, disabling output

Fails here: https://github.com/PX4/Firmware/blob/master/src/drivers/px4io/px4io_uploader.cpp#L138

**Comment by LorenzMeier** [comment] 2015-03-02 22:06
Does current master still fail for you?

**Comment by zottgrammes** [comment] 2015-03-02 22:10
I cherry picked 6646e3b onto my local copy of stable.

I'll flash master and try that.

**Comment by zottgrammes** [comment] 2015-03-02 22:44
Yeah, same problem on master: 8424325

**Comment by LorenzMeier** [comment] 2015-03-02 22:58
Bugger - I have not yet managed to reproduce. Could you look into this and maybe provide a patch which works locally?

**Comment by zottgrammes** [comment] 2015-03-04 00:03
I think I found it. px4io needs to be stopped when `px4io safety_on` fails. Not clear on the reason, I suspect there's a conflict with trying to access the bootloader and px4io itself.

Code snippet:

	if px4io start
	then
		# try to safe px4 io so motor outputs dont go crazy
		if px4io safety_on
		then
			# success! no-op
		else
			# px4io couldnt be safed, just shut it down
			px4io stop
		fi
	fi

**Comment by LorenzMeier** [comment] 2015-03-04 08:05
Thanks! The reason I missed this is that this only occurs if IO doesn't understand the safety command yet. So this happens mostly for people which update from a state a few weeks or months old, and it doesn't happen for people updating regularly. Sorry about that.
https://github.com/PX4/Firmware/pull/1879 fixes it.

**Comment by LorenzMeier** [comment] 2015-03-08 06:50
Could you please try master and report back?

**Comment by zottgrammes** [comment] 2015-03-09 18:20
I cherry picked this on my stable and it works. Thanks!
Do you stil lneed verificaiton on master branch?

**Closed** 2015-04-03 13:04 UTC
