### ISSUE TITLE
Motor spinning on USB power reset

### ISSUE THREAD

**Issue by lericson** [PX4/Firmware#7457] opened 2017-06-22 08:00 UTC
Despite the fixes in #7123, we still get motors spinning on unplugging the USB cable.

**Steps to reproduce**:
1. Plug in battery, USB cable
2. Start QGroundControl
3. Unplug USB cable

It only happens if QGroundControl has been talking to the PX4, as this triggers USB telemetry boolean that actually makes the PX4 reset after USB has been unplugged.

I have looked at the PWM signal with an oscilloscope and have pictures of it, but they aren't very telling.

**Workaround:**
In `src/modules/commander/commander.cpp`, find the `usleep()` just before the reboot and put `board_on_reset(0);` *before* the sleep. This sets all PWMs to zero.

A better long term fix would be to add a sleep to the `board_on_reset`.

**Comment by lericson** [comment] 2017-06-22 08:03
We have the PixRacer hardware version 4, by the way.

**Comment by davids5** [comment] 2017-06-22 15:25
@lericson - Thank you for reporting this. Please test https://github.com/PX4/Firmware/pull/7459

For a faster test cycle time: A `reboot` command on the debug port will also trigger the spin. 
It is tricky to catch. The asynchronous reset has to occur when the PWM pins are high. So more testing is better, testing with a logic analyzer with analog, is the best way to see the fix is solid. 

On the HW I tested the discharge rate was fast enough. I had assumed that is not the same on all HW and had the hook in place just incase. The PR use it.

**Comment by lericson** [comment] 2017-06-22 15:36
It happens very consistently for us. Will try the PR on Monday, thanks! I had tried usleep at the same location but it didn't work -- might've been to short an interval too.

**Comment by davids5** [comment] 2017-06-22 16:25
@lericson  
Thank you! Please let me know how the testing goes. I may also need more details the proposed fix you have and the HW attached.

**Comment by ndepal** [comment] 2017-06-27 10:41
Just happened to me as well with a PixRacer on master ca480ff.

**Comment by davids5** [comment] 2017-06-27 13:47
@ndepal Would you please test https://github.com/PX4/Firmware/pull/7459 and see if it stops the issue.

**Comment by ndepal** [comment] 2017-06-27 14:58
Just tested #7459, it does not fix the issue.

**Comment by davids5** [comment] 2017-06-27 15:26
@ndepal would you be able to do a few more tests?

1) Comment out the usleep found [here](https://github.com/PX4/Firmware/blob/9c25f93d09fd57387c35ae02688d20575a8ef027/src/modules/commander/commander.cpp#L2052) 

Does the motors still spin?

2) Add the sleep back in as `usleep(10000)`

Does the motors still spin?

These are just tests to try to understand where the PWM is getting stretched.

**Comment by ndepal** [comment] 2017-06-28 07:57
Tested as requested.

  1. motors still spin
  2. motors still spin

**Comment by davids5** [comment] 2017-06-28 17:12
@ndepal Thank you for testing.  

Would you mind one more test?

Do as @lericson suggested place the  `board_on_reset(0);` call prior to [this line](https://github.com/PX4/Firmware/blob/9c25f93d09fd57387c35ae02688d20575a8ef027/src/modules/commander/commander.cpp#L2052)

I will need to duplicate your setup. Please list what you have connected to the PixRacer and on what connector. Part number or links would be appreciated.

**Comment by ndepal** [comment] 2017-06-29 08:32
`board_on_reset(0);` fixes the problem for me, but only with a long enough sleep afterwards. I did not get spinning motors with `usleep(300000);` or above, but I did with `usleep(200000);` and below.

My setup:
Pixracer from auav.co
ESCs: [Favourite Little Bee 30A](https://hobbyking.com/en_us/favourite-little-bee-30a-2-6s-esc-no-bec.html?___store=en_us)
Motors: [Emax cooling MT2206 II 1900KV](http://www.helipal.com/emax-mt2206-v2-mini-cooling-motor-1900kv-ccw.html)
nothing else attached for these tests.

**Comment by davids5** [comment] 2017-06-29 13:02
@ndepal Thank you that is super helpful. I think I understand what is happening. See https://github.com/PX4/Firmware/pull/7459/commits/0484ee32239a9534db455b0cf3788440dfa3b92a for the details. I have updated https://github.com/PX4/Firmware/pull/7459. would you please fetch it again and test it with no other modification.

**Comment by ndepal** [comment] 2017-06-29 13:54
Pulled and re-tested #7459, the issue is fixed for me.

**Comment by davids5** [comment] 2017-06-29 15:09
@ndepal - thank you!

@lericson  I have updated #7459. would you please fetch it again and test it with no other modification.

**Comment by LorenzMeier** [comment] 2017-07-09 22:14
Should be fixed.

**Closed by LorenzMeier** 2017-07-09 22:14 UTC
Labels: bug, pixracer

**Comment by lericson** [comment] 2017-07-17 19:57
Can confirm it no longer happens. On a related note, we got the living crap scared out of us when our hexacopter started running its rotors full speed due to this. It even took off from the desk where it was seated, and not on USB reset either -- a simple reboot.
