### ISSUE TITLE
ekf_att_pos_estimator local altitude not relative to home on master

### ISSUE THREAD

**Issue by jgoppert** [PX4/Firmware#2079] opened 2015-04-24 18:33 UTC
I just flew with INAV_DISABLED and it looks like the altitude is absolute instead of relative.

**Comment by LorenzMeier** [comment] 2015-04-24 18:49
Could you upload a log on http://dash.oznet.ch? A recent log shows a zero-based local altitude:
http://dash.oznet.ch/view/BfkVZBTWJkQXJ56JdEEdi7

**Comment by Zefz** [comment] 2015-04-24 20:30
According to this
https://github.com/PX4/Firmware/blob/master/src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp#L814
the altitude should be zero relative to where the first baro update is processed:
https://github.com/PX4/Firmware/blob/master/src/modules/ekf_att_pos_estimator/ekf_att_pos_estimator_main.cpp#L1405

**Comment by surberj** [comment] 2015-05-29 12:29
We still have the issue that the local altitude is not set to zero before take-off. 
In ekf_att_pos_estimator_main.cpp, ~line 840, the _local_pos_z is calculated as:
_local_pos.z = _ekf->states[9] - _baro_ref_offset - _baroAltRef;

Wouldn't it make sense if the estimator itself (states[9]) would be initialized with 0, which involves that the _baroAltRef needs to be subtracted of the measurements instead of _local_pos.z?

Plot of our last flight:
![bildschirmfoto 2015-05-29 um 14 22 45](https://cloud.githubusercontent.com/assets/9253897/7882503/876102b0-060e-11e5-9cea-1977ae7508cc.png)
- SENS_BaroAlt starts at +340m
- _ekf->states[9] and _local_pos.z both start at -340m and are off by a very small factor (~0.02m).

**Comment by LorenzMeier** [comment] 2015-05-29 15:05
This is the global altitude in NED coordinates. The local altitude will read 0 - did you maybe have no GPS lock in that instance?

**Comment by surberj** [comment] 2015-06-01 09:41
Hi Lorenz, we have had GPS lock (between 8 and 10 satellites) and the GPS altitude starts at +410m:
![bildschirmfoto 2015-06-01 um 11 38 54](https://cloud.githubusercontent.com/assets/9253897/7910220/09ef9b4c-0853-11e5-8a1d-bddc3ca28bd5.png)
![bildschirmfoto 2015-06-01 um 11 39 07](https://cloud.githubusercontent.com/assets/9253897/7910221/0a0f57c0-0853-11e5-8d50-75665e50066f.png)

**Comment by LorenzMeier** [comment] 2015-06-02 09:08
Maybe this is a plotting problem? Does the LPOS_Z altitude overlap with yellow or not?

**Comment by surberj** [comment] 2015-06-02 09:16
It is not only a plotting problem - they overlap. The LPOS_Z alone looks like:
![bildschirmfoto 2015-06-02 um 11 11 27](https://cloud.githubusercontent.com/assets/9253897/7932381/2bb3db9c-0918-11e5-8fb9-7bdd4c2f5cc5.png)

By the way: The problem also occurs when we do not have GPS connection. It seems as if the offset _baroAltRef does not capture the "real" offset of the Baro.

**Comment by LorenzMeier** [comment] 2015-06-03 13:35
@surberj Would you have time to dive into the estimator and work out where the initialisation goes wrong?

**Comment by surberj** [comment] 2015-06-03 20:54
Yes, I'll investigate in that. I can start with it tomorrow.

**Comment by surberj** [comment] 2015-06-08 13:10
It looks as if the problem can be resolved by subtracting _baroAltRef from the baro measurements and initializing the estimator (states[9]) with zero.

I'll continue some testings on our platform and open a pull request on the repo wingtra/Firmware as soon as I am confident about the solution.

**Comment by LorenzMeier** [comment] 2015-06-08 13:15
I have a fix in the l1_fix branch. It had more considerations that needed to be taken of.

**Comment by surberj** [comment] 2015-06-08 13:28
Do you refer to the fix with the new function
void AttitudePositionEstimatorEKF::initReferencePosition(hrt_abstime timestamp,
	double lat, double lon, float gps_alt, float baro_alt)
on the branch l1_fix?

If yes, did you already test it? Do you know already when this will be merged into master? If the issue is resolved with that fix I do not have to investigate further in it I assume?

**Comment by LorenzMeier** [comment] 2015-06-08 13:49
Yes. Should be in master quite soon, depends mostly on testing bandwidth

**Comment by surberj** [comment] 2015-06-08 13:56
Ok, thanks!

**Comment by LorenzMeier** [comment] 2015-06-14 10:36
This is fixed. There is still an issue on filter resets that we need to resolve for the local position.

**Closed by LorenzMeier** 2015-06-14 10:36 UTC
