### ISSUE TITLE
Parameter ... not found on 272f1dd with Snapdragon

### ISSUE THREAD

**Issue by genemerewether** [PX4/Firmware#6263] opened 2017-01-05 23:00 UTC
- All calls to `param_get()` fail
- `param show *` displays no parameters
- Tried deleting params file with no change

Git bisect reveals [6fe9b8](https://github.com/PX4/Firmware/commit/6fe9b8e54351c8fe620f959b62ce1902b514f3ab) as the first bad commit

Tested with `make distclean` before building each commit

**Comment by bkueng** [comment] 2017-01-06 09:25
Same problem for `make posix_sitl_ekf2`. The problem is that https://github.com/PX4/Firmware/blob/master/cmake/configs/posix_sitl_ekf2.cmake uses an include for the module list which is not properly handled by the CMakeParser.

@mazahner can you look into that?

**Comment by bkueng** [comment] 2017-01-06 10:54
It's fixed now with https://github.com/PX4/Firmware/pull/6267. Leaving this open as it will need a proper fix.

**Comment by mazahner** [comment] 2017-01-06 12:33
I have not modified the CMakeParser which has been used to generate the px4_parameters.h/.cpp i just reused it during the generation of the parameters.xml (and therefore put it into it's own file). 
So if this has been working before, i wonder how the px4_paramters.h/.cpp have been generated before. Or does the sitl environment only rely on the .xml file?

I'll see what i can do...

**Comment by bkueng** [comment] 2017-01-06 13:10
I know. The problem was already there before, but it did not matter because the scope was not used. So you don't have to, but would be cool if you looked into it anyway.

**Comment by mhkabir** [comment] 2017-04-03 06:36
Is this still an issue?

**Comment by bkueng** [comment] 2017-04-03 07:02
No, we now use cmake directly to get the list of modules instead of parsing it with python.

**Closed by bkueng** 2017-04-03 07:02 UTC
Labels: bug
