### ISSUE TITLE
LPE local/global position estimation drift

### ISSUE THREAD

**Issue by Stifael** [PX4/Firmware#6140] opened 2016-12-22 15:01 UTC
In SITL teseted:
After taking off in manual mode and disarming such that the vehicle remains on the floor, the LPE gives wrong local/global position estimates (keeps drifting)

**Comment by jgoppert** [comment] 2016-12-22 15:16
Sounds like landed fake measurement isn't kicking in, will take a look soon.

**Comment by weiweikong** [comment] 2016-12-23 03:47
@Stifael Do you mean there is a minimum take off speed if we switch the mode to OFFBOARD when the vehicle is on the ground?

In the position control code, there is a section manage it
```
/* special thrust setpoint generation for takeoff from ground */
	if (_pos_sp_triplet.current.valid
	    && _pos_sp_triplet.current.type == position_setpoint_s::SETPOINT_TYPE_TAKEOFF
	    && _control_mode.flag_armed) {

		// check if we are not already in air.
		// if yes then we don't need a jumped takeoff anymore
		if (!_takeoff_jumped && !_vehicle_land_detected.landed && fabsf(_takeoff_thrust_sp) < FLT_EPSILON) {
			_takeoff_jumped = true;
		}

		if (!_takeoff_jumped) {
			// ramp thrust setpoint up
			if (_vel(2) > -(_params.tko_speed / 2.0f)) {
				_takeoff_thrust_sp += 0.5f * dt;
				_vel_sp.zero();
				_vel_prev.zero();

			} else {
				// copter has reached our takeoff speed. split the thrust setpoint up
				// into an integral part and into a P part
				_thrust_int(2) = _takeoff_thrust_sp - _params.vel_p(2) * fabsf(_vel(2));
				_thrust_int(2) = -math::constrain(_thrust_int(2), _params.thr_min, _params.thr_max);
				_vel_sp_prev(2) = -_params.tko_speed;
				_takeoff_jumped = true;
				_reset_int_z = false;
			}
		}

		if (_takeoff_jumped) {
			_vel_sp(2) = -_params.tko_speed;
		}

	}
```
but I am not confirmed that this section results the drifiting.

**Comment by Stifael** [comment] 2016-12-23 06:38
@weiweikong: nope, it has nothing to do with offboard mode. The values that you can see from qgc (global and local position lat, long, and alt) are sent from the estimator and is independent of the position controller. Those values are changing even when on ground after landing and disarming. this behaviour does not occur when using ekf2 estimator

**Comment by jgoppert** [comment] 2016-12-23 06:45
I'm kind of being stretched thin. I'm trying to get the IEKF running as a replacement to LPE/ attitude_estimator_q and also keep maintaining LPE during the transition. @Stifael before I start debugging   can  you give me more info on if you were flying with optical flow or gps?

**Comment by jgoppert** [comment] 2016-12-23 06:57
@Stifael I'm unable to reproduce with GPS, will try flow.

**Comment by jgoppert** [comment] 2016-12-23 07:05
@Stifael 

```bash
make posix_sitl_default iris_opt_flow
```

takeoff and land using optical flow in SITl: http://logs.px4.io/plot_app?log=016bf446-ff28-4cc6-a287-695b9e33b42b

```bash
make posix_sitl_default iris_opt_flow
```
I just now saw it after running the optical flow sim:

```bash
pxh> commandINFO  [local_position_estimator] [lpe] baro init 0 m std -2147483648 cm
INFO  [commander] home: 47.3977432, 8.5455942, 0.10
INFO  [tone_alarm] home_set
er takeoff
pxh> INFO  [commander] Taking off
INFO  [tone_alarm] positive
INFO  [commander] home: 47.3977432, 8.5455942, 0.13
INFO  [tone_alarm] arming
INFO  [commander] Takeoff detected
INFO  [local_position_estimator] [lpe] land timeout 
INFO  [tone_alarm] neutral
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris/imu, deleting message. This warning is printed only once.
[Wrn] [Publisher.cc:140] Queue limit reached for topic /gazebo/default/iris/motor_speed/1, deleting message. This warning is printed only once.
WARN  [navigator] global position timeout
INFO  [tone_alarm] gps_warning
INFO  [commander] no gps
WARN  [commander] failsafe mode on
ERROR [sensors] Baro #0 fail:  STALE!
```

http://logs.px4.io/plot_app?log=d5496997-6bdc-4eb1-8c8d-84d9b80c3d2e

**Comment by weiweikong** [comment] 2016-12-23 08:38
@Stifael Thank you for your explain. I will read the code and test more to find the strange period, taking off aggressively, when uses LPE, as mentioned in issue https://github.com/PX4/Firmware/issues/6106.

**Closed** 2016-12-23 20:08 UTC
