### ISSUE TITLE
Logging doesn't work

### ISSUE THREAD

**Issue by DrTon** [PX4/Firmware#2107] opened 2015-04-30 13:14 UTC
Logging doesn't work in current master (tested on multirotor config). I suspect because of 6d41b5d. If this is true then "stable" is also affected. @LorenzMeier, maybe it's time to go away from descriptor-based topics and do more careful testing of "stable"?

**Comment by tumbili** [comment] 2015-05-03 13:16
@DrTon Logging works for me on latest master (Tested with IRIS). Can you retry your setup? And what exactly do you mean by "not working"?

**Comment by DrTon** [comment] 2015-05-03 19:26
Not working means no log files after flight. Have you recompiled NuttX and using default parameters (INAV_ENABLED=1)? Will try again, maybe something already changed.

**Comment by tumbili** [comment] 2015-05-04 08:46
@DrTon Recompiled NuttX and made sure INAV is running. Still logging works. Let me know if it works for you.

**Comment by DrTon** [comment] 2015-05-11 17:13
I think I know why it's "not working". Right now (11 may 2015) I got the following:
```
telem> [sdlog2] log dir: /fs/microsd/log/2015-04-23
telem> [sdlog2] starting: 13_05_52.px4log
```
IMO it's better to have sess001/log001 in case of no GPS...

**Comment by kd0aij** [comment] 2015-05-11 17:16
#2084 may be related

**Comment by LorenzMeier** [comment] 2015-05-17 16:29
I've addressed this in https://github.com/PX4/Firmware/pull/2191. There is fundamentally nothing intelligent we can do about clock drift, other than offering developers the choice to rely on GPS only. For outdoor operations the RTC backed mode makes a lot of sense though.

**Comment by LorenzMeier** [comment] 2015-05-17 16:29
Closing, please refer to the PR.

**Closed by LorenzMeier** 2015-05-17 16:29 UTC
Labels: bug, multicopter, multiplatform, priority-critical

**Comment by DrTon** [comment] 2015-05-17 16:32
One day error after day of sleeping is not a DRIFT :) it's a bug somewhere in RTC.

**Comment by kd0aij** [comment] 2015-05-17 16:47
One would hope that the battery backup would last for more than a day or
two...
The MS5621 appears to have a 5.5mah capacity, while the processor has a
worst-case draw of 11ua.
5.5mah/11ua = 20.8 days
Unless, of course, something else is loading Vbat...



On Sun, May 17, 2015 at 10:32 AM, Anton Babushkin <notifications@github.com>
wrote:

> One day error after day of sleeping is not a DRIFT :) it's a bug somewhere
> in RTC.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PX4/Firmware/issues/2107#issuecomment-102820737>.
>



-- 
Mark Whitehorn
kd0aij@gmail.com

**Comment by kd0aij** [comment] 2015-05-17 16:48
BTW, typical Vbat mode current draw is spec'd at 1.6ua, for an endurance of
143 days


On Sun, May 17, 2015 at 10:47 AM, Mark Whitehorn <kd0aij@gmail.com> wrote:

> One would hope that the battery backup would last for more than a day or
> two...
> The MS5621 appears to have a 5.5mah capacity, while the processor has a
> worst-case draw of 11ua.
> 5.5mah/11ua = 20.8 days
> Unless, of course, something else is loading Vbat...
>
>
>
> On Sun, May 17, 2015 at 10:32 AM, Anton Babushkin <
> notifications@github.com> wrote:
>
>> One day error after day of sleeping is not a DRIFT :) it's a bug
>> somewhere in RTC.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/PX4/Firmware/issues/2107#issuecomment-102820737>.
>>
>
>
>
> --
> Mark Whitehorn
> kd0aij@gmail.com
>



-- 
Mark Whitehorn
kd0aij@gmail.com

**Comment by LorenzMeier** [comment] 2015-05-17 16:58
@DrTon I can't reproduce - what steps do I need to do to recreate your case?

**Comment by kd0aij** [comment] 2015-05-17 17:03
Was this perhaps an FMUv1?
