### ISSUE TITLE
Altitude control in beta allows full pitch down

### ISSUE THREAD

**Issue by AndreasAntener** [PX4/Firmware#2611] opened 2015-07-27 10:40 UTC
@LorenzMeier
In altctl/posctl with beta the plane pitches down fully (vertical descent) when I give it full pitch down input. Altitude control kicks in again when I let go, but it has to climb back up again then to whatever altitude it was supposed to hold. Pitching up does not have this effect.

(I flew with #2610)

**Comment by LorenzMeier** [comment] 2015-07-27 10:44
That's expected and won't be fixed for this release. We will re-introduce altitude climb rate limits on the next one.

**Comment by LorenzMeier** [comment] 2015-07-27 10:44
That's expected and will only be fixed on the next release.

**Comment by LorenzMeier** [comment] 2015-07-27 10:45
Could I have the log file from the flight though? I'd love to see if the init issues are gone.

**Comment by AndreasAntener** [comment] 2015-07-27 11:43
What were the initial issues? I also flew hil just before you pushed the fix and it did very weird stuff in posctl, almost tumbling, which I blamed on my setup at first..

http://dash.oznet.ch/view/DRKiL3NJebyAG4GUqtzR5D
![screen shot 2015-07-27 at 13 38 23](https://cloud.githubusercontent.com/assets/5750020/8905262/1540b1fa-3465-11e5-84c1-582fc6c27d49.png)

**Comment by kd0aij** [comment] 2015-07-27 13:09
@AndreasAntener Looks like you had a long walk to retrieve that plane!

**Comment by AndreasAntener** [comment] 2015-07-27 13:13
;)

**Comment by kd0aij** [comment] 2015-07-29 20:41
I flew Beta (Firmware Version	75085dc) yesterday on two different planes. Behaved reasonably will on the Ninox, which is now tuned fairly well for pitch control, but I also observed a steep full throttle dive at full down pitch command. This behavior is certainly undesirable, if not a bug in the TECS logic:
![altctl](https://cloud.githubusercontent.com/assets/2300221/8969286/8a80cff4-35ff-11e5-86c0-3de3ba96d7a8.png)

The Acromaster, which is not yet properly tuned, also exhibited the full throttle dive, but zero pitch resulted in fairly rapid altitude gain, making altctl unusable.
![altctl_bug](https://cloud.githubusercontent.com/assets/2300221/8969317/d6b78836-35ff-11e5-96a3-575c715b37da.png)

**Comment by LorenzMeier** [comment] 2015-07-29 21:03
@kd0aij I need the log file, I can't make sense of it yet.

**Comment by kd0aij** [comment] 2015-07-29 23:06
Acromaster flight report: https://docs.google.com/document/d/1sAEtfk8iRfWeuABWV2IDBuEOunTv3p-vg-9zigMXScg/edit?usp=sharing

Ninox flight report: https://drive.google.com/open?id=1-h1CpWUT3PzXXIJUXEtE2UIwhBlr5SSotWPyibBkvlE

**Comment by LorenzMeier** [comment] 2015-08-17 07:49
Fixed.

**Closed by LorenzMeier** 2015-08-17 07:49 UTC
